-- AI Watch Auth Migration
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New Query)

-- 1. users table
CREATE TABLE IF NOT EXISTS users (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email             VARCHAR(255) UNIQUE NOT NULL,
  full_name         VARCHAR(255) NOT NULL,
  company           VARCHAR(255),
  role              VARCHAR(50) NOT NULL DEFAULT 'other',
  password_hash     VARCHAR(255),
  oauth_provider    VARCHAR(50),
  oauth_id          VARCHAR(255),
  is_verified       BOOLEAN DEFAULT FALSE,
  email_verified_at TIMESTAMPTZ,
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

-- 2. refresh_tokens table
CREATE TABLE IF NOT EXISTS refresh_tokens (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash  VARCHAR(255) UNIQUE NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 3. password_reset_tokens table
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash  VARCHAR(255) UNIQUE NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  used_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 4. email_verification_tokens table
CREATE TABLE IF NOT EXISTS email_verification_tokens (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash  VARCHAR(255) UNIQUE NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  used_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 5. newsletter_subscribers table
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  email         TEXT PRIMARY KEY,
  subscribed_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. reports table (per-user, max 30)
CREATE TABLE IF NOT EXISTS reports (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID REFERENCES users(id) ON DELETE SET NULL,
  title      TEXT,
  content    JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_users_email           ON users(email);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_hash   ON refresh_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_reset_tokens_hash     ON password_reset_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_verify_tokens_hash    ON email_verification_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_reports_user_id       ON reports(user_id);

-- Migrations for existing databases (safe to run on already-created tables)
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS company VARCHAR(255);

-- ── V4 Sprint 2: saved_items table ───────────────────────────────────────────
-- Stores bookmarked articles and watchlisted trends per user.
-- item_type: 'article' | 'trend'
-- item_id:   article DB id or trend id (stored as TEXT for flexibility)
-- item_data: snapshot of display fields (title, source, signal, etc.)
-- UNIQUE (user_id, item_id) prevents duplicate saves silently.

CREATE TABLE IF NOT EXISTS saved_items (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  item_type  VARCHAR(20) NOT NULL CHECK (item_type IN ('article', 'trend')),
  item_id    TEXT        NOT NULL,
  item_data  JSONB       NOT NULL DEFAULT '{}',
  saved_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, item_id)
);

CREATE INDEX IF NOT EXISTS idx_saved_items_user_id   ON saved_items(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_items_type      ON saved_items(user_id, item_type);
CREATE INDEX IF NOT EXISTS idx_saved_items_saved_at  ON saved_items(saved_at DESC);

-- ── V4: alert_preferences table ───────────────────────────────────────────────
-- Stores per-user email alert preferences for Feature 5 (Email Alerts).
-- Each user gets one row. unsubscribe_token is auto-generated by trigger on INSERT.

CREATE TABLE IF NOT EXISTS alert_preferences (
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  keywords          TEXT[]      NOT NULL DEFAULT ARRAY[]::TEXT[],
  min_signal_score  INTEGER     NOT NULL DEFAULT 7 CHECK (min_signal_score >= 1 AND min_signal_score <= 10),
  enabled           BOOLEAN     NOT NULL DEFAULT FALSE,
  last_sent_at      TIMESTAMPTZ,
  unsubscribe_token TEXT        UNIQUE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_alert_prefs_user_id           ON alert_preferences(user_id);
CREATE INDEX IF NOT EXISTS idx_alert_prefs_enabled           ON alert_preferences(enabled);
CREATE INDEX IF NOT EXISTS idx_alert_prefs_unsubscribe_token ON alert_preferences(unsubscribe_token);

-- Trigger function: auto-generate a 64-char hex unsubscribe token on INSERT
-- Uses gen_random_bytes(32) → 32 bytes → 64 hex chars (cryptographically random)
CREATE OR REPLACE FUNCTION set_alert_unsubscribe_token()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.unsubscribe_token IS NULL THEN
    NEW.unsubscribe_token := encode(gen_random_bytes(32), 'hex');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach trigger — fires before each INSERT on alert_preferences
DROP TRIGGER IF EXISTS trg_alert_prefs_unsubscribe_token ON alert_preferences;
CREATE TRIGGER trg_alert_prefs_unsubscribe_token
  BEFORE INSERT ON alert_preferences
  FOR EACH ROW
  EXECUTE FUNCTION set_alert_unsubscribe_token();

-- Verification queries (run after migration to confirm everything is set up):
-- SELECT * FROM alert_preferences LIMIT 1;
-- SELECT indexname FROM pg_indexes WHERE tablename = 'alert_preferences';
-- INSERT INTO alert_preferences (user_id, keywords, enabled)
--   VALUES (gen_random_uuid(), ARRAY['OpenAI'], true)
--   RETURNING unsubscribe_token;
-- Expected: 64-char hex string e.g. a1b2c3d4e5f6...
