// Auto-generated — maps page number to local image path
export const NEWSLETTER_IMAGES = {
  1: { title: "tttthhhhuuuurrrrssssddddaaaayyyy aaaapppprrrriiiillll 11", path: "/newsletter-images/page001_tttthhhhuuuurrrrssssddddaaaayyyy_____aaaapppprrrriiiillll_11.jpg" },
  2: { title: "quality at the heart of the adm seminar", path: "/newsletter-images/page002_quality_at_the_heart_of_the_adm_seminar.jpg" },
  3: { title: "achievements", path: "/newsletter-images/page003_achievements.png" },
  4: { title: "a strategic partnership with umnia bank", path: "/newsletter-images/page004_a_strategic_partnership_with_umnia_bank.jpg" },
  5: { title: "hybrid work mode reminder mandatory", path: "/newsletter-images/page005_hybrid_work_mode_reminder___mandatory.jpg" },
  6: { title: "the collaboration also supports the digital explorers progra", path: "/newsletter-images/page006_the_collaboration_also_supports_the_digital_explorers_progra.jpg" },
  7: { title: "dei policy toward a strengthened", path: "/newsletter-images/page007_dei_policy_toward_a_strengthened.jpg" },
  8: { title: "well-being nutrition town hall with a specialist in partne", path: "/newsletter-images/page008_well-being___nutrition_town_hall_with_a_specialist_in_partne.jpg" },
  9: { title: "done", path: "/newsletter-images/page009_done.jpg" },
  10: { title: "new contracts strengthening our", path: "/newsletter-images/page010_new_contracts_strengthening_our.jpg" },
  11: { title: "delivers key strategic initiatives", path: "/newsletter-images/page011_delivers_key_strategic_initiatives.png" },
  12: { title: "in the spotlight our svp lamiaa", path: "/newsletter-images/page012_in_the_spotlight_our_svp_lamiaa.jpg" },
  13: { title: "recharge thrive this ramadan with", path: "/newsletter-images/page013_recharge___thrive_this_ramadan_with.jpg" },
  14: { title: "launch of the partnership with cr dit du", path: "/newsletter-images/page014_launch_of_the_partnership_with_cr_dit_du.jpg" },
  15: { title: "dxc cares turning commitment into", path: "/newsletter-images/page015_dxc_cares_turning_commitment_into.jpg" },
  16: { title: "international women s day event march 10th", path: "/newsletter-images/page016_international_women_s_day_event___march_10th.jpg" },
  17: { title: "moussali omar est off looping mire mohamed", path: "/newsletter-images/page017__moussali__omar_est_off___looping__mire__mohamed.jpg" },
  18: { title: "merci pour votre collabora0on habituelle", path: "/newsletter-images/page018_merci_pour_votre_collabora0on_habituelle.jpg" },
  19: { title: "iiiimmmmppppoooorrrrttttaaaannnncccceeee high", path: "/newsletter-images/page019_iiiimmmmppppoooorrrrttttaaaannnncccceeee_high.jpg" },
  20: { title: "new contracts strengthening our", path: "/newsletter-images/page020_new_contracts_strengthening_our.jpg" },
  21: { title: "delivers key strategic initiatives", path: "/newsletter-images/page021_delivers_key_strategic_initiatives.png" },
  22: { title: "in the spotlight our svp lamiaa", path: "/newsletter-images/page022_in_the_spotlight_our_svp_lamiaa.jpg" },
  23: { title: "fy26 vow preparations are underway", path: "/newsletter-images/page023_fy26_vow_preparations_are_underway_.jpg" },
  24: { title: "innovation at work voices that inspire", path: "/newsletter-images/page024_innovation_at_work_voices_that_inspire.jpg" },
  25: { title: "setting to connect reinforce bonds and foster collective m", path: "/newsletter-images/page025_setting_to_connect__reinforce_bonds__and_foster_collective_m.jpg" },
  26: { title: "product owner senior hf", path: "/newsletter-images/page026_product_owner_senior_hf_.jpg" },
  27: { title: "oneteam rewards ramadan edition wrap-up - march 31st", path: "/newsletter-images/page027_oneteam_rewards_ramadan_edition_wrap-up_-_march_31st.jpg" },
  28: { title: "d am lioration garantissant une coute proactive et continu", path: "/newsletter-images/page028_d_am_lioration__garantissant_une__coute_proactive_et_continu.jpg" },
  29: { title: "un immense merci toutes les quipes impliqu es dans la pr", path: "/newsletter-images/page029_un_immense_merci___toutes_les__quipes_impliqu_es_dans_la_pr_.jpg" },
  30: { title: "pour rester comp titifs et garantir une performance p renne", path: "/newsletter-images/page030_pour_rester_comp_titifs_et_garantir_une_performance_p_renne_.jpg" },
  31: { title: "gestion documentaire", path: "/newsletter-images/page031_gestion_documentaire.jpg" },
  32: { title: "nouvelle version de la politique qualit partag e avec tou", path: "/newsletter-images/page032___nouvelle_version_de_la_politique_qualit__partag_e_avec_tou.jpg" },
  33: { title: "avec un score csat de 4 5 nous avons", path: "/newsletter-images/page033_avec_un_score_csat_de_4_5__nous_avons.jpg" },
  34: { title: "audit votre rigueur votre", path: "/newsletter-images/page034_audit__votre_rigueur__votre.jpg" },
  35: { title: "pour rester comp titifs et garantir une", path: "/newsletter-images/page035_pour_rester_comp_titifs_et_garantir_une.jpg" },
  36: { title: "2 town halls r alis s", path: "/newsletter-images/page036_2_town_halls_r_alis_s.jpg" },
  37: { title: "merci chacun pour votre implication et votre", path: "/newsletter-images/page037_merci___chacun_pour_votre_implication_et_votre.jpg" },
  38: { title: "avec un score csat de 4 5 nous avons", path: "/newsletter-images/page038_avec_un_score_csat_de_4_5__nous_avons.jpg" },
  39: { title: "audit votre rigueur votre", path: "/newsletter-images/page039_audit__votre_rigueur__votre.jpg" },
  40: { title: "pour rester comp titifs et garantir une", path: "/newsletter-images/page040_pour_rester_comp_titifs_et_garantir_une.jpg" },
  41: { title: "2 town halls r alis s", path: "/newsletter-images/page041_2_town_halls_r_alis_s.jpg" },
  42: { title: "ttttoooo moussali omar", path: "/newsletter-images/page042_ttttoooo_moussali__omar.jpg" },
  43: { title: "avec un score csat de 4 5 nous", path: "/newsletter-images/page043_avec_un_score_csat_de_4_5__nous.jpg" },
  44: { title: "audit corporate une performance", path: "/newsletter-images/page044_audit_corporate_une_performance.jpg" },
  45: { title: "r f rence en mati re de qualit et", path: "/newsletter-images/page045_r_f_rence_en_mati_re_de_qualit__et.jpg" },
  46: { title: "ce semestre nous renfor ons nos", path: "/newsletter-images/page046_ce_semestre__nous_renfor_ons_nos.jpg" },
  47: { title: "performante et durable", path: "/newsletter-images/page047_performante_et_durable_.jpg" },
  48: { title: "reporting dynamique cette", path: "/newsletter-images/page048_reporting_dynamique__cette.jpg" },
  49: { title: "pppprrrroooommmmoooottttoooorrrr ssssccccoooorrrreeee", path: "/newsletter-images/page049_pppprrrroooommmmoooottttoooorrrr_ssssccccoooorrrreeee.jpg" },
  50: { title: "atteindre ce niveau d excellence", path: "/newsletter-images/page050_atteindre_ce_niveau_d_excellence_.jpg" },
  51: { title: "ce semestre nous renfor ons nos", path: "/newsletter-images/page051_ce_semestre__nous_renfor_ons_nos.jpg" },
  52: { title: "performante et durable", path: "/newsletter-images/page052_performante_et_durable_.jpg" },
  53: { title: "strengthening global collaboration eu sales leadership", path: "/newsletter-images/page053_strengthening_global_collaboration_eu_sales_leadership.jpg" },
  54: { title: "key achievements strengthening our role as a strategic", path: "/newsletter-images/page054_key_achievements_strengthening_our_role_as_a_strategic.jpg" },
  55: { title: "managerial charter leading with flexibility and agility", path: "/newsletter-images/page055_managerial_charter_leading_with_flexibility_and_agility.jpg" },
  56: { title: "health insurance made clear simplifying benefits for you", path: "/newsletter-images/page056_health_insurance_made_clear__simplifying_benefits_for_you.jpg" },
  57: { title: "kudos to our dxc cdg football teams for an outstanding", path: "/newsletter-images/page057_kudos_to_our_dxc_cdg_football_teams_for_an_outstanding.jpg" },
  58: { title: "ethics compliance week key highlights", path: "/newsletter-images/page058_ethics___compliance_week_key_highlights.jpg" },
  59: { title: "afcon 2025 concepts soon", path: "/newsletter-images/page059_afcon_2025_concepts___soon.jpg" },
  60: { title: "ffffrrrroooommmm oneteam communication", path: "/newsletter-images/page060_ffffrrrroooommmm_oneteam_communication.jpg" },
  61: { title: "spotlight on managerial and relational effectiveness", path: "/newsletter-images/page061_spotlight_on_managerial_and_relational_effectiveness.jpg" },
  62: { title: "team spirit in motion dxc cdg at the casablanca marathon", path: "/newsletter-images/page062_team_spirit_in_motion_dxc_cdg_at_the_casablanca_marathon_.jpg" },
  63: { title: "ethics compliance week 2025 in full swing", path: "/newsletter-images/page063_ethics___compliance_week_2025_in_full_swing.jpg" },
  64: { title: "thank you for making pink october a success", path: "/newsletter-images/page064_thank_you_for_making_pink_october_a_success.jpg" },
  65: { title: "movember awareness events for men s health dates to be a", path: "/newsletter-images/page065_movember___awareness_events_for_men_s_health___dates_to_be_a.jpg" },
  66: { title: "tttthhhhuuuurrrrssssddddaaaayyyy aaaapppprrrriiiillll 11", path: "/newsletter-images/page066_tttthhhhuuuurrrrssssddddaaaayyyy_____aaaapppprrrriiiillll_11.jpg" },
  67: { title: "offshore strength continuity and new horizons", path: "/newsletter-images/page067_offshore_strength_continuity_and_new_horizons_.jpg" },
  68: { title: "five prestigious offshore visits mark a strong first semeste", path: "/newsletter-images/page068_five_prestigious_offshore_visits_mark_a_strong_first_semeste.jpg" },
  69: { title: "excellence in action our local client successes", path: "/newsletter-images/page069_excellence_in_action_our_local_client_successes.jpg" },
  70: { title: "oneteam rewards celebrating our top employees", path: "/newsletter-images/page070_oneteam_rewards_celebrating_our_top_employees_.jpg" },
  71: { title: "dxc cdg shines with 4 brandon hall group excellence awards", path: "/newsletter-images/page071_dxc_cdg_shines_with_4_brandon_hall_group_excellence_awards_.jpg" },
  72: { title: "pink october solidarity walk casablanca sunday 12th", path: "/newsletter-images/page072_pink_october_solidarity_walk___casablanca_sunday_12th.jpg" },
  73: { title: "ffffrrrroooommmm moussali omar omar moussali dxc com", path: "/newsletter-images/page073_ffffrrrroooommmm_moussali__omar_omar_moussali_dxc_com.jpg" },
  74: { title: "74 of 212", path: "/newsletter-images/page074_74_of_212.jpg" },
  78: { title: "0 non-conformit s majeures", path: "/newsletter-images/page078_0_non-conformit_s_majeures.jpg" },
  80: { title: "ce semestre nous renfor ons nos pratiques qualit pour am l", path: "/newsletter-images/page080_ce_semestre__nous_renfor_ons_nos_pratiques_qualit__pour_am_l.jpg" },
  81: { title: "summer 2025 edition", path: "/newsletter-images/page081_summer_2025_edition.jpg" },
  82: { title: "update to travel and expense policy in morocco internati", path: "/newsletter-images/page082_update_to_travel_and_expense_policy___in_morocco___internati.jpg" },
  83: { title: "dxc cdg wins jmse championship again", path: "/newsletter-images/page083_dxc_cdg_wins_jmse_championship_again_.jpg" },
  84: { title: "kickoff of fy26 managerial charter program", path: "/newsletter-images/page084_kickoff_of_fy26__managerial_charter__program.jpg" },
  85: { title: "oneteam rewards edition wrap-up", path: "/newsletter-images/page085_oneteam_rewards_edition_wrap-up_.jpg" },
  86: { title: "dxc cdg earns cgem csr label", path: "/newsletter-images/page086_dxc_cdg_earns_cgem_csr_label_.jpg" },
  87: { title: "tttthhhhuuuurrrrssssddddaaaayyyy aaaapppprrrriiiillll 11", path: "/newsletter-images/page087_tttthhhhuuuurrrrssssddddaaaayyyy_____aaaapppprrrriiiillll_11.jpg" },
  88: { title: "tttthhhhuuuurrrrssssddddaaaayyyy", path: "/newsletter-images/page088_tttthhhhuuuurrrrssssddddaaaayyyy____.jpg" },
  89: { title: "april 2025", path: "/newsletter-images/page089_april_2025.jpg" },
  90: { title: "this year we took our values of engagement and sharing to n", path: "/newsletter-images/page090_this_year__we_took_our_values_of_engagement_and_sharing_to_n.jpg" },
  91: { title: "dxc cdg management seminar a strong start to fy26", path: "/newsletter-images/page091_dxc_cdg_management_seminar_a_strong_start_to_fy26_.jpg" },
  92: { title: "a transparent look at our voice of workforce results a step", path: "/newsletter-images/page092_a_transparent_look_at_our_voice_of_workforce_results_a_step.jpg" },
  93: { title: "every step reflected our values of well-being resilience a", path: "/newsletter-images/page093_every_step_reflected_our_values_of_well-being__resilience__a.jpg" },
  94: { title: "may 11th - inpt forum the may 15th 16th - future of work", path: "/newsletter-images/page094_may_11th_-_inpt_forum_the_may_15th___16th_-_future_of_work.jpg" },
  95: { title: "smoking cessation workshop", path: "/newsletter-images/page095_smoking_cessation_workshop.jpg" },
  96: { title: "dxc cdg launches its ai center of excellence", path: "/newsletter-images/page096_dxc_cdg_launches_its_ai_center_of_excellence.jpg" },
  97: { title: "a look back at our recent town hall with leadership", path: "/newsletter-images/page097_a_look_back_at_our_recent_town_hall_with_leadership.jpg" },
  98: { title: "join the cooptation challenge", path: "/newsletter-images/page098_join_the_cooptation_challenge_.jpg" },
  99: { title: "this initiative reflects our commitment to eco-friendly prac", path: "/newsletter-images/page099_this_initiative_reflects_our_commitment_to_eco-friendly_prac.jpg" },
  100: { title: "of the year ranking", path: "/newsletter-images/page100_of_the_year_ranking.jpg" },
  101: { title: "renewing our commitment to excellence", path: "/newsletter-images/page101_renewing_our_commitment_to_excellence.jpg" },
  102: { title: "a strong start to the year marked by success", path: "/newsletter-images/page102_a_strong_start_to_the_year_marked_by_success.jpg" },
  103: { title: "our colleague shines at the seville marathon 2025", path: "/newsletter-images/page103_our_colleague_shines_at_the_seville_marathon_2025.jpg" },
  104: { title: "our participation to the cese hearings on care economy", path: "/newsletter-images/page104_our_participation_to_the_cese_hearings_on_care_economy.jpg" },
  105: { title: "have you got any other", path: "/newsletter-images/page105_have_you_got_any_other.jpg" },
  106: { title: "tttthhhhuuuurrrrssssddddaaaayyyy aaaapppprrrriiiillll 11", path: "/newsletter-images/page106_tttthhhhuuuurrrrssssddddaaaayyyy_____aaaapppprrrriiiillll_11.jpg" },
  107: { title: "total energy", path: "/newsletter-images/page107_total_energy.jpg" },
  108: { title: "londonmarket team connects and embraces", path: "/newsletter-images/page108_londonmarket_team_connects_and_embraces.jpg" },
  109: { title: "december health and well-being awareness at dxc cdg", path: "/newsletter-images/page109_december_health_and_well-being_awareness_at_dxc_cdg.jpg" },
  110: { title: "ben m sik forum casablanca", path: "/newsletter-images/page110_ben_m_sik_forum___casablanca.jpg" },
  111: { title: "have you got any other", path: "/newsletter-images/page111_have_you_got_any_other.jpg" },
  112: { title: "tttthhhhuuuurrrrssssddddaaaayyyy aaaapppprrrriiiillll 11", path: "/newsletter-images/page112_tttthhhhuuuurrrrssssddddaaaayyyy_____aaaapppprrrriiiillll_11.jpg" },
  113: { title: "discover the part 1 of the answers to the", path: "/newsletter-images/page113_discover_the_part_1_of_the_answers_to_the.jpg" },
  114: { title: "kick-off 2nd edition of the national program digital explor", path: "/newsletter-images/page114_kick-off_2nd_edition_of_the_national_program__digital_explor.jpg" },
  115: { title: "movember raising awareness about men s health prostate cance", path: "/newsletter-images/page115_movember_raising_awareness_about_men_s_health_prostate_cance.jpg" },
  116: { title: "gen ai summit 2024 - insights on ai digital transformation", path: "/newsletter-images/page116_gen_ai_summit_2024_-_insights_on_ai___digital_transformation.jpg" },
  117: { title: "fy25 s1 review strengthened partnership and shared trust", path: "/newsletter-images/page117_fy25_s1_review_strengthened_partnership_and_shared_trust.jpg" },
  118: { title: "well-being launch of dxc talks", path: "/newsletter-images/page118_well-being_launch_of_dxc_talks.jpg" },
  119: { title: "discover the part 1 of the answers to the", path: "/newsletter-images/page119_discover_the_part_1_of_the_answers_to_the.jpg" },
  120: { title: "environmental awareness waste management", path: "/newsletter-images/page120_environmental_awareness_waste_management.jpg" },
  121: { title: "rabat business school 5th edition careers expo forum", path: "/newsletter-images/page121_rabat_business_school_5th_edition_careers_expo__forum.jpg" },
  122: { title: "special gathering jmse champions 2024", path: "/newsletter-images/page122_special_gathering_jmse_champions_2024.jpg" },
  123: { title: "amcham networking gala - thanksgiving dinner", path: "/newsletter-images/page123_amcham_networking_gala_-_thanksgiving_dinner.jpg" },
  124: { title: "client success community driving operational excellence cu", path: "/newsletter-images/page124_client_success_community_driving_operational_excellence___cu.jpg" },
  125: { title: "well-being launch of dxc talks", path: "/newsletter-images/page125_well-being_launch_of_dxc_talks.jpg" },
  126: { title: "dear all", path: "/newsletter-images/page126_dear_all_.jpg" },
  127: { title: "127 of 212", path: "/newsletter-images/page127_127_of_212.jpg" },
  128: { title: "128 of 212", path: "/newsletter-images/page128_128_of_212.jpg" },
  129: { title: "129 of 212", path: "/newsletter-images/page129_129_of_212.jpg" },
  130: { title: "130 of 212", path: "/newsletter-images/page130_130_of_212.jpg" },
  131: { title: "131 of 212", path: "/newsletter-images/page131_131_of_212.jpg" },
  132: { title: "132 of 212", path: "/newsletter-images/page132_132_of_212.jpg" },
  133: { title: "133 of 212", path: "/newsletter-images/page133_133_of_212.jpg" },
  134: { title: "business focus", path: "/newsletter-images/page134_business_focus.jpg" },
  135: { title: "in september dxc cdg had the privilege of", path: "/newsletter-images/page135_in_september__dxc_cdg_had_the_privilege_of.jpg" },
  136: { title: "excellence in action our local", path: "/newsletter-images/page136_excellence_in_action_our_local.jpg" },
  137: { title: "international experts", path: "/newsletter-images/page137_international_experts_.jpg" },
  138: { title: "let s keep cultivating a collaborative and", path: "/newsletter-images/page138_let_s_keep_cultivating_a_collaborative_and.jpg" },
  139: { title: "pink october solidarity walk", path: "/newsletter-images/page139_pink_october_solidarity_walk__.jpg" },
  140: { title: "business focus", path: "/newsletter-images/page140_business_focus.jpg" },
  141: { title: "creation and operational excellence the", path: "/newsletter-images/page141_creation__and_operational_excellence__the.jpg" },
  142: { title: "excellence in action our local", path: "/newsletter-images/page142_excellence_in_action_our_local.jpg" },
  143: { title: "decision-makers including ministers and", path: "/newsletter-images/page143_decision-makers__including_ministers_and.jpg" },
  144: { title: "brandon hall group excellence gold", path: "/newsletter-images/page144_brandon_hall_group_excellence_gold.jpg" },
  145: { title: "if you wish to unsubscribe from our newsletter click here", path: "/newsletter-images/page145_if_you_wish_to_unsubscribe_from_our_newsletter__click_here.jpg" },
  146: { title: "isb leadership visit strengthening", path: "/newsletter-images/page146_isb_leadership_visit_strengthening.jpg" },
  147: { title: "for the second year in a row dxc cdg has", path: "/newsletter-images/page147_for_the_second_year_in_a_row__dxc_cdg_has.jpg" },
  148: { title: "dxc cdg at the heart of africa s", path: "/newsletter-images/page148_dxc_cdg_at_the_heart_of_africa_s.jpg" },
  149: { title: "dxc cdg shines with 4 brandon", path: "/newsletter-images/page149_dxc_cdg_shines_with_4_brandon.jpg" },
  150: { title: "if you wish to unsubscribe from our newsletter click here", path: "/newsletter-images/page150_if_you_wish_to_unsubscribe_from_our_newsletter__click_here.jpg" },
  151: { title: "offshore strength continuity and", path: "/newsletter-images/page151_offshore_strength_continuity_and.jpg" },
  152: { title: "five prestigious offshore visits", path: "/newsletter-images/page152_five_prestigious_offshore_visits.jpg" },
  153: { title: "some of the recent key projects include", path: "/newsletter-images/page153_some_of_the_recent_key_projects_include.jpg" },
  154: { title: "if you weren t in the top 10 this time don t worry", path: "/newsletter-images/page154_if_you_weren_t_in_the_top_10_this_time__don_t_worry_.jpg" },
  155: { title: "employees with everything they need to", path: "/newsletter-images/page155_employees_with_everything_they_need_to.jpg" },
  156: { title: "at technopolis at", path: "/newsletter-images/page156_at_technopolis___at.jpg" },
  157: { title: "new horizons", path: "/newsletter-images/page157_new_horizons_.jpg" },
  158: { title: "exciting growth extending our", path: "/newsletter-images/page158_exciting_growth_extending_our.jpg" },
  159: { title: "um6p provision of on-site", path: "/newsletter-images/page159_um6p___provision_of_on-site.jpg" },
  160: { title: "6th samir haouchi casablanca client-", path: "/newsletter-images/page160_6th_samir_haouchi___casablanca_client-.jpg" },
  161: { title: "breaks", path: "/newsletter-images/page161_breaks_.jpg" },
  162: { title: "offshore strength continuity and", path: "/newsletter-images/page162_offshore_strength_continuity_and.jpg" },
  163: { title: "five prestigious offshore visits", path: "/newsletter-images/page163_five_prestigious_offshore_visits.jpg" },
  164: { title: "consolidated existing projects renewed", path: "/newsletter-images/page164_consolidated_existing_projects__renewed.jpg" },
  165: { title: "our top employees", path: "/newsletter-images/page165_our_top_employees_.jpg" },
  166: { title: "game on casablanca office gets", path: "/newsletter-images/page166_game_on_casablanca_office_gets.jpg" },
  167: { title: "if you wish to unsubscribe from our newsletter click here", path: "/newsletter-images/page167_if_you_wish_to_unsubscribe_from_our_newsletter__click_here.jpg" },
  168: { title: "of our solutions in addressing our clients", path: "/newsletter-images/page168_of_our_solutions_in_addressing_our_clients_.jpg" },
  169: { title: "teams for assure claims and", path: "/newsletter-images/page169_teams_for_assure_claims_and.jpg" },
  170: { title: "dxc cdg at the heart of africa s", path: "/newsletter-images/page170_dxc_cdg_at_the_heart_of_africa_s.jpg" },
  171: { title: "dxc cdg shines with 4 brandon", path: "/newsletter-images/page171_dxc_cdg_shines_with_4_brandon.jpg" },
  172: { title: "pink october solidarity walk", path: "/newsletter-images/page172_pink_october_solidarity_walk__.jpg" },
  173: { title: "ddddaaaatttteeee tuesday 29 july 2025 at 164547 gmt 0100", path: "/newsletter-images/page173_ddddaaaatttteeee_tuesday__29_july_2025_at_164547_gmt_0100.jpg" },
  174: { title: "and partnerships", path: "/newsletter-images/page174_and_partnerships.jpg" },
  175: { title: "proud to be part of the 17th edition", path: "/newsletter-images/page175_proud_to_be_part_of_the_17th_edition.jpg" },
  176: { title: "wrapping up the 1st edition of", path: "/newsletter-images/page176_wrapping_up_the_1st_edition_of.jpg" },
  177: { title: "the recent town hall held with our quality team", path: "/newsletter-images/page177_the_recent_town_hall_held_with_our_quality_team.jpg" },
  178: { title: "registrations are open let s go for gold", path: "/newsletter-images/page178_registrations_are_open__let_s_go_for_gold_.jpg" },
  179: { title: "intelligence edge", path: "/newsletter-images/page179_intelligence_edge.jpg" },
  180: { title: "april 2025", path: "/newsletter-images/page180_april_2025.jpg" },
  181: { title: "another win worth celebrating", path: "/newsletter-images/page181_another_win_worth_celebrating_.jpg" },
  182: { title: "dxc cdg management seminar a", path: "/newsletter-images/page182_dxc_cdg_management_seminar_a.jpg" },
  183: { title: "a transparent look at our voice of", path: "/newsletter-images/page183_a_transparent_look_at_our_voice_of.jpg" },
  184: { title: "colleagues from across dxc cdg took on the", path: "/newsletter-images/page184_colleagues_from_across_dxc_cdg_took_on_the.jpg" },
  185: { title: "may 11th - inpt forum the", path: "/newsletter-images/page185_may_11th_-_inpt_forum_the.jpg" },
  186: { title: "may 15th 16th - future of work in", path: "/newsletter-images/page186_may_15th___16th_-_future_of_work_in.jpg" },
  187: { title: "inside gitex africa 2025 dxc", path: "/newsletter-images/page187_inside_gitex_africa_2025_dxc.jpg" },
  188: { title: "this partnership is a clear reflection of our", path: "/newsletter-images/page188_this_partnership_is_a_clear_reflection_of_our.jpg" },
  189: { title: "this seminar marked not only the start of a", path: "/newsletter-images/page189_this_seminar_marked_not_only_the_start_of_a.jpg" },
  190: { title: "dxc cdg launches its quality", path: "/newsletter-images/page190_dxc_cdg_launches_its_quality.jpg" },
  191: { title: "entreprise this june", path: "/newsletter-images/page191_entreprise_this_june_.jpg" },
  192: { title: "may 8th - healthy cooking", path: "/newsletter-images/page192_may_8th_-_healthy_cooking.jpg" },
  193: { title: "april 2025", path: "/newsletter-images/page193_april_2025.jpg" },
  194: { title: "another win worth celebrating", path: "/newsletter-images/page194_another_win_worth_celebrating_.jpg" },
  195: { title: "dxc cdg management seminar a", path: "/newsletter-images/page195_dxc_cdg_management_seminar_a.jpg" },
  196: { title: "together", path: "/newsletter-images/page196_together_.jpg" },
  197: { title: "dxc cdg gears up for jmse 2025", path: "/newsletter-images/page197_dxc_cdg_gears_up_for_jmse_2025.jpg" },
  198: { title: "may 11th - inpt forum the", path: "/newsletter-images/page198_may_11th_-_inpt_forum_the.jpg" },
  199: { title: "if you wish to unsubscribe from our newsletter click here", path: "/newsletter-images/page199_if_you_wish_to_unsubscribe_from_our_newsletter__click_here.jpg" },
  200: { title: "kickoff of fy26 managerial charter", path: "/newsletter-images/page200_kickoff_of_fy26_managerial_charter.jpg" },
  201: { title: "dxc cdg shines at the tamouda", path: "/newsletter-images/page201_dxc_cdg_shines_at_the_tamouda.jpg" },
  202: { title: "a journey of", path: "/newsletter-images/page202_a_journey_of.jpg" },
  203: { title: "dxc cdg earns cgem csr label", path: "/newsletter-images/page203_dxc_cdg_earns_cgem_csr_label_.jpg" },
  204: { title: "smoking cessation workshop", path: "/newsletter-images/page204_smoking_cessation_workshop.jpg" },
  205: { title: "inside gitex africa 2025 dxc", path: "/newsletter-images/page205_inside_gitex_africa_2025_dxc.jpg" },
  206: { title: "impact solutions and building long-term trust-", path: "/newsletter-images/page206_impact_solutions_and_building_long-term__trust-.jpg" },
  207: { title: "new fiscal year but also a renewed", path: "/newsletter-images/page207_new_fiscal_year_but_also_a_renewed.jpg" },
  208: { title: "dxc cdg launches its quality", path: "/newsletter-images/page208_dxc_cdg_launches_its_quality.jpg" },
  209: { title: "dxc cdg gears up for jmse 2025", path: "/newsletter-images/page209_dxc_cdg_gears_up_for_jmse_2025.jpg" },
  210: { title: "may 11th - inpt forum the", path: "/newsletter-images/page210_may_11th_-_inpt_forum_the.jpg" },
  211: { title: "if you wish to unsubscribe from our newsletter click here", path: "/newsletter-images/page211_if_you_wish_to_unsubscribe_from_our_newsletter__click_here.png" },
};

export const IMAGE_BY_TITLE = {
  "tttthhhhuuuurrrrssssddddaaaayyyy aaaapppprrrriiiillll 11": "/newsletter-images/page001_tttthhhhuuuurrrrssssddddaaaayyyy_____aaaapppprrrriiiillll_11.jpg",
  "quality at the heart of the adm seminar": "/newsletter-images/page002_quality_at_the_heart_of_the_adm_seminar.jpg",
  "achievements": "/newsletter-images/page003_achievements.png",
  "a strategic partnership with umnia bank": "/newsletter-images/page004_a_strategic_partnership_with_umnia_bank.jpg",
  "hybrid work mode reminder mandatory": "/newsletter-images/page005_hybrid_work_mode_reminder___mandatory.jpg",
  "the collaboration also supports the digital explorers progra": "/newsletter-images/page006_the_collaboration_also_supports_the_digital_explorers_progra.jpg",
  "dei policy toward a strengthened": "/newsletter-images/page007_dei_policy_toward_a_strengthened.jpg",
  "well-being nutrition town hall with a specialist in partne": "/newsletter-images/page008_well-being___nutrition_town_hall_with_a_specialist_in_partne.jpg",
  "done": "/newsletter-images/page009_done.jpg",
  "new contracts strengthening our": "/newsletter-images/page010_new_contracts_strengthening_our.jpg",
  "delivers key strategic initiatives": "/newsletter-images/page011_delivers_key_strategic_initiatives.png",
  "in the spotlight our svp lamiaa": "/newsletter-images/page012_in_the_spotlight_our_svp_lamiaa.jpg",
  "recharge thrive this ramadan with": "/newsletter-images/page013_recharge___thrive_this_ramadan_with.jpg",
  "launch of the partnership with cr dit du": "/newsletter-images/page014_launch_of_the_partnership_with_cr_dit_du.jpg",
  "dxc cares turning commitment into": "/newsletter-images/page015_dxc_cares_turning_commitment_into.jpg",
  "international women s day event march 10th": "/newsletter-images/page016_international_women_s_day_event___march_10th.jpg",
  "moussali omar est off looping mire mohamed": "/newsletter-images/page017__moussali__omar_est_off___looping__mire__mohamed.jpg",
  "merci pour votre collabora0on habituelle": "/newsletter-images/page018_merci_pour_votre_collabora0on_habituelle.jpg",
  "iiiimmmmppppoooorrrrttttaaaannnncccceeee high": "/newsletter-images/page019_iiiimmmmppppoooorrrrttttaaaannnncccceeee_high.jpg",
  "new contracts strengthening our": "/newsletter-images/page020_new_contracts_strengthening_our.jpg",
  "delivers key strategic initiatives": "/newsletter-images/page021_delivers_key_strategic_initiatives.png",
  "in the spotlight our svp lamiaa": "/newsletter-images/page022_in_the_spotlight_our_svp_lamiaa.jpg",
  "fy26 vow preparations are underway": "/newsletter-images/page023_fy26_vow_preparations_are_underway_.jpg",
  "innovation at work voices that inspire": "/newsletter-images/page024_innovation_at_work_voices_that_inspire.jpg",
  "setting to connect reinforce bonds and foster collective m": "/newsletter-images/page025_setting_to_connect__reinforce_bonds__and_foster_collective_m.jpg",
  "product owner senior hf": "/newsletter-images/page026_product_owner_senior_hf_.jpg",
  "oneteam rewards ramadan edition wrap-up - march 31st": "/newsletter-images/page027_oneteam_rewards_ramadan_edition_wrap-up_-_march_31st.jpg",
  "d am lioration garantissant une coute proactive et continu": "/newsletter-images/page028_d_am_lioration__garantissant_une__coute_proactive_et_continu.jpg",
  "un immense merci toutes les quipes impliqu es dans la pr": "/newsletter-images/page029_un_immense_merci___toutes_les__quipes_impliqu_es_dans_la_pr_.jpg",
  "pour rester comp titifs et garantir une performance p renne": "/newsletter-images/page030_pour_rester_comp_titifs_et_garantir_une_performance_p_renne_.jpg",
  "gestion documentaire": "/newsletter-images/page031_gestion_documentaire.jpg",
  "nouvelle version de la politique qualit partag e avec tou": "/newsletter-images/page032___nouvelle_version_de_la_politique_qualit__partag_e_avec_tou.jpg",
  "avec un score csat de 4 5 nous avons": "/newsletter-images/page033_avec_un_score_csat_de_4_5__nous_avons.jpg",
  "audit votre rigueur votre": "/newsletter-images/page034_audit__votre_rigueur__votre.jpg",
  "pour rester comp titifs et garantir une": "/newsletter-images/page035_pour_rester_comp_titifs_et_garantir_une.jpg",
  "2 town halls r alis s": "/newsletter-images/page036_2_town_halls_r_alis_s.jpg",
  "merci chacun pour votre implication et votre": "/newsletter-images/page037_merci___chacun_pour_votre_implication_et_votre.jpg",
  "avec un score csat de 4 5 nous avons": "/newsletter-images/page038_avec_un_score_csat_de_4_5__nous_avons.jpg",
  "audit votre rigueur votre": "/newsletter-images/page039_audit__votre_rigueur__votre.jpg",
  "pour rester comp titifs et garantir une": "/newsletter-images/page040_pour_rester_comp_titifs_et_garantir_une.jpg",
  "2 town halls r alis s": "/newsletter-images/page041_2_town_halls_r_alis_s.jpg",
  "ttttoooo moussali omar": "/newsletter-images/page042_ttttoooo_moussali__omar.jpg",
  "avec un score csat de 4 5 nous": "/newsletter-images/page043_avec_un_score_csat_de_4_5__nous.jpg",
  "audit corporate une performance": "/newsletter-images/page044_audit_corporate_une_performance.jpg",
  "r f rence en mati re de qualit et": "/newsletter-images/page045_r_f_rence_en_mati_re_de_qualit__et.jpg",
  "ce semestre nous renfor ons nos": "/newsletter-images/page046_ce_semestre__nous_renfor_ons_nos.jpg",
  "performante et durable": "/newsletter-images/page047_performante_et_durable_.jpg",
  "reporting dynamique cette": "/newsletter-images/page048_reporting_dynamique__cette.jpg",
  "pppprrrroooommmmoooottttoooorrrr ssssccccoooorrrreeee": "/newsletter-images/page049_pppprrrroooommmmoooottttoooorrrr_ssssccccoooorrrreeee.jpg",
  "atteindre ce niveau d excellence": "/newsletter-images/page050_atteindre_ce_niveau_d_excellence_.jpg",
  "ce semestre nous renfor ons nos": "/newsletter-images/page051_ce_semestre__nous_renfor_ons_nos.jpg",
  "performante et durable": "/newsletter-images/page052_performante_et_durable_.jpg",
  "strengthening global collaboration eu sales leadership": "/newsletter-images/page053_strengthening_global_collaboration_eu_sales_leadership.jpg",
  "key achievements strengthening our role as a strategic": "/newsletter-images/page054_key_achievements_strengthening_our_role_as_a_strategic.jpg",
  "managerial charter leading with flexibility and agility": "/newsletter-images/page055_managerial_charter_leading_with_flexibility_and_agility.jpg",
  "health insurance made clear simplifying benefits for you": "/newsletter-images/page056_health_insurance_made_clear__simplifying_benefits_for_you.jpg",
  "kudos to our dxc cdg football teams for an outstanding": "/newsletter-images/page057_kudos_to_our_dxc_cdg_football_teams_for_an_outstanding.jpg",
  "ethics compliance week key highlights": "/newsletter-images/page058_ethics___compliance_week_key_highlights.jpg",
  "afcon 2025 concepts soon": "/newsletter-images/page059_afcon_2025_concepts___soon.jpg",
  "ffffrrrroooommmm oneteam communication": "/newsletter-images/page060_ffffrrrroooommmm_oneteam_communication.jpg",
  "spotlight on managerial and relational effectiveness": "/newsletter-images/page061_spotlight_on_managerial_and_relational_effectiveness.jpg",
  "team spirit in motion dxc cdg at the casablanca marathon": "/newsletter-images/page062_team_spirit_in_motion_dxc_cdg_at_the_casablanca_marathon_.jpg",
  "ethics compliance week 2025 in full swing": "/newsletter-images/page063_ethics___compliance_week_2025_in_full_swing.jpg",
  "thank you for making pink october a success": "/newsletter-images/page064_thank_you_for_making_pink_october_a_success.jpg",
  "movember awareness events for men s health dates to be a": "/newsletter-images/page065_movember___awareness_events_for_men_s_health___dates_to_be_a.jpg",
  "tttthhhhuuuurrrrssssddddaaaayyyy aaaapppprrrriiiillll 11": "/newsletter-images/page066_tttthhhhuuuurrrrssssddddaaaayyyy_____aaaapppprrrriiiillll_11.jpg",
  "offshore strength continuity and new horizons": "/newsletter-images/page067_offshore_strength_continuity_and_new_horizons_.jpg",
  "five prestigious offshore visits mark a strong first semeste": "/newsletter-images/page068_five_prestigious_offshore_visits_mark_a_strong_first_semeste.jpg",
  "excellence in action our local client successes": "/newsletter-images/page069_excellence_in_action_our_local_client_successes.jpg",
  "oneteam rewards celebrating our top employees": "/newsletter-images/page070_oneteam_rewards_celebrating_our_top_employees_.jpg",
  "dxc cdg shines with 4 brandon hall group excellence awards": "/newsletter-images/page071_dxc_cdg_shines_with_4_brandon_hall_group_excellence_awards_.jpg",
  "pink october solidarity walk casablanca sunday 12th": "/newsletter-images/page072_pink_october_solidarity_walk___casablanca_sunday_12th.jpg",
  "ffffrrrroooommmm moussali omar omar moussali dxc com": "/newsletter-images/page073_ffffrrrroooommmm_moussali__omar_omar_moussali_dxc_com.jpg",
  "74 of 212": "/newsletter-images/page074_74_of_212.jpg",
  "0 non-conformit s majeures": "/newsletter-images/page078_0_non-conformit_s_majeures.jpg",
  "ce semestre nous renfor ons nos pratiques qualit pour am l": "/newsletter-images/page080_ce_semestre__nous_renfor_ons_nos_pratiques_qualit__pour_am_l.jpg",
  "summer 2025 edition": "/newsletter-images/page081_summer_2025_edition.jpg",
  "update to travel and expense policy in morocco internati": "/newsletter-images/page082_update_to_travel_and_expense_policy___in_morocco___internati.jpg",
  "dxc cdg wins jmse championship again": "/newsletter-images/page083_dxc_cdg_wins_jmse_championship_again_.jpg",
  "kickoff of fy26 managerial charter program": "/newsletter-images/page084_kickoff_of_fy26__managerial_charter__program.jpg",
  "oneteam rewards edition wrap-up": "/newsletter-images/page085_oneteam_rewards_edition_wrap-up_.jpg",
  "dxc cdg earns cgem csr label": "/newsletter-images/page086_dxc_cdg_earns_cgem_csr_label_.jpg",
  "tttthhhhuuuurrrrssssddddaaaayyyy aaaapppprrrriiiillll 11": "/newsletter-images/page087_tttthhhhuuuurrrrssssddddaaaayyyy_____aaaapppprrrriiiillll_11.jpg",
  "tttthhhhuuuurrrrssssddddaaaayyyy": "/newsletter-images/page088_tttthhhhuuuurrrrssssddddaaaayyyy____.jpg",
  "april 2025": "/newsletter-images/page089_april_2025.jpg",
  "this year we took our values of engagement and sharing to n": "/newsletter-images/page090_this_year__we_took_our_values_of_engagement_and_sharing_to_n.jpg",
  "dxc cdg management seminar a strong start to fy26": "/newsletter-images/page091_dxc_cdg_management_seminar_a_strong_start_to_fy26_.jpg",
  "a transparent look at our voice of workforce results a step": "/newsletter-images/page092_a_transparent_look_at_our_voice_of_workforce_results_a_step.jpg",
  "every step reflected our values of well-being resilience a": "/newsletter-images/page093_every_step_reflected_our_values_of_well-being__resilience__a.jpg",
  "may 11th - inpt forum the may 15th 16th - future of work": "/newsletter-images/page094_may_11th_-_inpt_forum_the_may_15th___16th_-_future_of_work.jpg",
  "smoking cessation workshop": "/newsletter-images/page095_smoking_cessation_workshop.jpg",
  "dxc cdg launches its ai center of excellence": "/newsletter-images/page096_dxc_cdg_launches_its_ai_center_of_excellence.jpg",
  "a look back at our recent town hall with leadership": "/newsletter-images/page097_a_look_back_at_our_recent_town_hall_with_leadership.jpg",
  "join the cooptation challenge": "/newsletter-images/page098_join_the_cooptation_challenge_.jpg",
  "this initiative reflects our commitment to eco-friendly prac": "/newsletter-images/page099_this_initiative_reflects_our_commitment_to_eco-friendly_prac.jpg",
  "of the year ranking": "/newsletter-images/page100_of_the_year_ranking.jpg",
  "renewing our commitment to excellence": "/newsletter-images/page101_renewing_our_commitment_to_excellence.jpg",
  "a strong start to the year marked by success": "/newsletter-images/page102_a_strong_start_to_the_year_marked_by_success.jpg",
  "our colleague shines at the seville marathon 2025": "/newsletter-images/page103_our_colleague_shines_at_the_seville_marathon_2025.jpg",
  "our participation to the cese hearings on care economy": "/newsletter-images/page104_our_participation_to_the_cese_hearings_on_care_economy.jpg",
  "have you got any other": "/newsletter-images/page105_have_you_got_any_other.jpg",
  "tttthhhhuuuurrrrssssddddaaaayyyy aaaapppprrrriiiillll 11": "/newsletter-images/page106_tttthhhhuuuurrrrssssddddaaaayyyy_____aaaapppprrrriiiillll_11.jpg",
  "total energy": "/newsletter-images/page107_total_energy.jpg",
  "londonmarket team connects and embraces": "/newsletter-images/page108_londonmarket_team_connects_and_embraces.jpg",
  "december health and well-being awareness at dxc cdg": "/newsletter-images/page109_december_health_and_well-being_awareness_at_dxc_cdg.jpg",
  "ben m sik forum casablanca": "/newsletter-images/page110_ben_m_sik_forum___casablanca.jpg",
  "have you got any other": "/newsletter-images/page111_have_you_got_any_other.jpg",
  "tttthhhhuuuurrrrssssddddaaaayyyy aaaapppprrrriiiillll 11": "/newsletter-images/page112_tttthhhhuuuurrrrssssddddaaaayyyy_____aaaapppprrrriiiillll_11.jpg",
  "discover the part 1 of the answers to the": "/newsletter-images/page113_discover_the_part_1_of_the_answers_to_the.jpg",
  "kick-off 2nd edition of the national program digital explor": "/newsletter-images/page114_kick-off_2nd_edition_of_the_national_program__digital_explor.jpg",
  "movember raising awareness about men s health prostate cance": "/newsletter-images/page115_movember_raising_awareness_about_men_s_health_prostate_cance.jpg",
  "gen ai summit 2024 - insights on ai digital transformation": "/newsletter-images/page116_gen_ai_summit_2024_-_insights_on_ai___digital_transformation.jpg",
  "fy25 s1 review strengthened partnership and shared trust": "/newsletter-images/page117_fy25_s1_review_strengthened_partnership_and_shared_trust.jpg",
  "well-being launch of dxc talks": "/newsletter-images/page118_well-being_launch_of_dxc_talks.jpg",
  "discover the part 1 of the answers to the": "/newsletter-images/page119_discover_the_part_1_of_the_answers_to_the.jpg",
  "environmental awareness waste management": "/newsletter-images/page120_environmental_awareness_waste_management.jpg",
  "rabat business school 5th edition careers expo forum": "/newsletter-images/page121_rabat_business_school_5th_edition_careers_expo__forum.jpg",
  "special gathering jmse champions 2024": "/newsletter-images/page122_special_gathering_jmse_champions_2024.jpg",
  "amcham networking gala - thanksgiving dinner": "/newsletter-images/page123_amcham_networking_gala_-_thanksgiving_dinner.jpg",
  "client success community driving operational excellence cu": "/newsletter-images/page124_client_success_community_driving_operational_excellence___cu.jpg",
  "well-being launch of dxc talks": "/newsletter-images/page125_well-being_launch_of_dxc_talks.jpg",
  "dear all": "/newsletter-images/page126_dear_all_.jpg",
  "127 of 212": "/newsletter-images/page127_127_of_212.jpg",
  "128 of 212": "/newsletter-images/page128_128_of_212.jpg",
  "129 of 212": "/newsletter-images/page129_129_of_212.jpg",
  "130 of 212": "/newsletter-images/page130_130_of_212.jpg",
  "131 of 212": "/newsletter-images/page131_131_of_212.jpg",
  "132 of 212": "/newsletter-images/page132_132_of_212.jpg",
  "133 of 212": "/newsletter-images/page133_133_of_212.jpg",
  "business focus": "/newsletter-images/page134_business_focus.jpg",
  "in september dxc cdg had the privilege of": "/newsletter-images/page135_in_september__dxc_cdg_had_the_privilege_of.jpg",
  "excellence in action our local": "/newsletter-images/page136_excellence_in_action_our_local.jpg",
  "international experts": "/newsletter-images/page137_international_experts_.jpg",
  "let s keep cultivating a collaborative and": "/newsletter-images/page138_let_s_keep_cultivating_a_collaborative_and.jpg",
  "pink october solidarity walk": "/newsletter-images/page139_pink_october_solidarity_walk__.jpg",
  "business focus": "/newsletter-images/page140_business_focus.jpg",
  "creation and operational excellence the": "/newsletter-images/page141_creation__and_operational_excellence__the.jpg",
  "excellence in action our local": "/newsletter-images/page142_excellence_in_action_our_local.jpg",
  "decision-makers including ministers and": "/newsletter-images/page143_decision-makers__including_ministers_and.jpg",
  "brandon hall group excellence gold": "/newsletter-images/page144_brandon_hall_group_excellence_gold.jpg",
  "if you wish to unsubscribe from our newsletter click here": "/newsletter-images/page145_if_you_wish_to_unsubscribe_from_our_newsletter__click_here.jpg",
  "isb leadership visit strengthening": "/newsletter-images/page146_isb_leadership_visit_strengthening.jpg",
  "for the second year in a row dxc cdg has": "/newsletter-images/page147_for_the_second_year_in_a_row__dxc_cdg_has.jpg",
  "dxc cdg at the heart of africa s": "/newsletter-images/page148_dxc_cdg_at_the_heart_of_africa_s.jpg",
  "dxc cdg shines with 4 brandon": "/newsletter-images/page149_dxc_cdg_shines_with_4_brandon.jpg",
  "if you wish to unsubscribe from our newsletter click here": "/newsletter-images/page150_if_you_wish_to_unsubscribe_from_our_newsletter__click_here.jpg",
  "offshore strength continuity and": "/newsletter-images/page151_offshore_strength_continuity_and.jpg",
  "five prestigious offshore visits": "/newsletter-images/page152_five_prestigious_offshore_visits.jpg",
  "some of the recent key projects include": "/newsletter-images/page153_some_of_the_recent_key_projects_include.jpg",
  "if you weren t in the top 10 this time don t worry": "/newsletter-images/page154_if_you_weren_t_in_the_top_10_this_time__don_t_worry_.jpg",
  "employees with everything they need to": "/newsletter-images/page155_employees_with_everything_they_need_to.jpg",
  "at technopolis at": "/newsletter-images/page156_at_technopolis___at.jpg",
  "new horizons": "/newsletter-images/page157_new_horizons_.jpg",
  "exciting growth extending our": "/newsletter-images/page158_exciting_growth_extending_our.jpg",
  "um6p provision of on-site": "/newsletter-images/page159_um6p___provision_of_on-site.jpg",
  "6th samir haouchi casablanca client-": "/newsletter-images/page160_6th_samir_haouchi___casablanca_client-.jpg",
  "breaks": "/newsletter-images/page161_breaks_.jpg",
  "offshore strength continuity and": "/newsletter-images/page162_offshore_strength_continuity_and.jpg",
  "five prestigious offshore visits": "/newsletter-images/page163_five_prestigious_offshore_visits.jpg",
  "consolidated existing projects renewed": "/newsletter-images/page164_consolidated_existing_projects__renewed.jpg",
  "our top employees": "/newsletter-images/page165_our_top_employees_.jpg",
  "game on casablanca office gets": "/newsletter-images/page166_game_on_casablanca_office_gets.jpg",
  "if you wish to unsubscribe from our newsletter click here": "/newsletter-images/page167_if_you_wish_to_unsubscribe_from_our_newsletter__click_here.jpg",
  "of our solutions in addressing our clients": "/newsletter-images/page168_of_our_solutions_in_addressing_our_clients_.jpg",
  "teams for assure claims and": "/newsletter-images/page169_teams_for_assure_claims_and.jpg",
  "dxc cdg at the heart of africa s": "/newsletter-images/page170_dxc_cdg_at_the_heart_of_africa_s.jpg",
  "dxc cdg shines with 4 brandon": "/newsletter-images/page171_dxc_cdg_shines_with_4_brandon.jpg",
  "pink october solidarity walk": "/newsletter-images/page172_pink_october_solidarity_walk__.jpg",
  "ddddaaaatttteeee tuesday 29 july 2025 at 164547 gmt 0100": "/newsletter-images/page173_ddddaaaatttteeee_tuesday__29_july_2025_at_164547_gmt_0100.jpg",
  "and partnerships": "/newsletter-images/page174_and_partnerships.jpg",
  "proud to be part of the 17th edition": "/newsletter-images/page175_proud_to_be_part_of_the_17th_edition.jpg",
  "wrapping up the 1st edition of": "/newsletter-images/page176_wrapping_up_the_1st_edition_of.jpg",
  "the recent town hall held with our quality team": "/newsletter-images/page177_the_recent_town_hall_held_with_our_quality_team.jpg",
  "registrations are open let s go for gold": "/newsletter-images/page178_registrations_are_open__let_s_go_for_gold_.jpg",
  "intelligence edge": "/newsletter-images/page179_intelligence_edge.jpg",
  "april 2025": "/newsletter-images/page180_april_2025.jpg",
  "another win worth celebrating": "/newsletter-images/page181_another_win_worth_celebrating_.jpg",
  "dxc cdg management seminar a": "/newsletter-images/page182_dxc_cdg_management_seminar_a.jpg",
  "a transparent look at our voice of": "/newsletter-images/page183_a_transparent_look_at_our_voice_of.jpg",
  "colleagues from across dxc cdg took on the": "/newsletter-images/page184_colleagues_from_across_dxc_cdg_took_on_the.jpg",
  "may 11th - inpt forum the": "/newsletter-images/page185_may_11th_-_inpt_forum_the.jpg",
  "may 15th 16th - future of work in": "/newsletter-images/page186_may_15th___16th_-_future_of_work_in.jpg",
  "inside gitex africa 2025 dxc": "/newsletter-images/page187_inside_gitex_africa_2025_dxc.jpg",
  "this partnership is a clear reflection of our": "/newsletter-images/page188_this_partnership_is_a_clear_reflection_of_our.jpg",
  "this seminar marked not only the start of a": "/newsletter-images/page189_this_seminar_marked_not_only_the_start_of_a.jpg",
  "dxc cdg launches its quality": "/newsletter-images/page190_dxc_cdg_launches_its_quality.jpg",
  "entreprise this june": "/newsletter-images/page191_entreprise_this_june_.jpg",
  "may 8th - healthy cooking": "/newsletter-images/page192_may_8th_-_healthy_cooking.jpg",
  "april 2025": "/newsletter-images/page193_april_2025.jpg",
  "another win worth celebrating": "/newsletter-images/page194_another_win_worth_celebrating_.jpg",
  "dxc cdg management seminar a": "/newsletter-images/page195_dxc_cdg_management_seminar_a.jpg",
  "together": "/newsletter-images/page196_together_.jpg",
  "dxc cdg gears up for jmse 2025": "/newsletter-images/page197_dxc_cdg_gears_up_for_jmse_2025.jpg",
  "may 11th - inpt forum the": "/newsletter-images/page198_may_11th_-_inpt_forum_the.jpg",
  "if you wish to unsubscribe from our newsletter click here": "/newsletter-images/page199_if_you_wish_to_unsubscribe_from_our_newsletter__click_here.jpg",
  "kickoff of fy26 managerial charter": "/newsletter-images/page200_kickoff_of_fy26_managerial_charter.jpg",
  "dxc cdg shines at the tamouda": "/newsletter-images/page201_dxc_cdg_shines_at_the_tamouda.jpg",
  "a journey of": "/newsletter-images/page202_a_journey_of.jpg",
  "dxc cdg earns cgem csr label": "/newsletter-images/page203_dxc_cdg_earns_cgem_csr_label_.jpg",
  "smoking cessation workshop": "/newsletter-images/page204_smoking_cessation_workshop.jpg",
  "inside gitex africa 2025 dxc": "/newsletter-images/page205_inside_gitex_africa_2025_dxc.jpg",
  "impact solutions and building long-term trust-": "/newsletter-images/page206_impact_solutions_and_building_long-term__trust-.jpg",
  "new fiscal year but also a renewed": "/newsletter-images/page207_new_fiscal_year_but_also_a_renewed.jpg",
  "dxc cdg launches its quality": "/newsletter-images/page208_dxc_cdg_launches_its_quality.jpg",
  "dxc cdg gears up for jmse 2025": "/newsletter-images/page209_dxc_cdg_gears_up_for_jmse_2025.jpg",
  "may 11th - inpt forum the": "/newsletter-images/page210_may_11th_-_inpt_forum_the.jpg",
  "if you wish to unsubscribe from our newsletter click here": "/newsletter-images/page211_if_you_wish_to_unsubscribe_from_our_newsletter__click_here.png",
};

export const KEY_IMAGES = {
  gitex: "/newsletter-images/page011_delivers_key_strategic_initiatives.png",
  adm: "/newsletter-images/page002_quality_at_the_heart_of_the_adm_seminar.jpg",
  achievements: "/newsletter-images/page003_achievements.png",
  umnia: "/newsletter-images/page004_a_strategic_partnership_with_umnia_bank.jpg",
  dei: "/newsletter-images/page007_dei_policy_toward_a_strengthened.jpg",
  wellbeing: "/newsletter-images/page008_well-being___nutrition_town_hall_with_a_specialist_in_partne.jpg",
  contracts: "/newsletter-images/page010_new_contracts_strengthening_our.jpg",
  svp_lamiaa: "/newsletter-images/page012_in_the_spotlight_our_svp_lamiaa.jpg",
  ramadan: "/newsletter-images/page013_recharge___thrive_this_ramadan_with.jpg",
  iwd: "/newsletter-images/page016_international_women_s_day_event___march_10th.jpg",
  vow: "/newsletter-images/page023_fy26_vow_preparations_are_underway_.jpg",
  innovation: "/newsletter-images/page024_innovation_at_work_voices_that_inspire.jpg",
  cares: "/newsletter-images/page015_dxc_cares_turning_commitment_into.jpg",
  credit_du_maroc: "/newsletter-images/page014_launch_of_the_partnership_with_cr_dit_du.jpg",
};
