// ─── SHARED DATA — All 12 months ONETEAM FY25-FY26 ────────────────────────────

export const CATEGORY_IMAGES = {
  "Business & Clients":   { grad: "linear-gradient(135deg,#1a0d00,#3d1f00)", icon: "💼", accent: "#FFB476" },
  "Quality":              { grad: "linear-gradient(135deg,#052e16,#064e3b)", icon: "🏅", accent: "#4ADE80" },
  "Innovation & Tech":    { grad: "linear-gradient(135deg,#0f172a,#1e3a5f)", icon: "🤖", accent: "#60A5FA" },
  "CSR & Community":      { grad: "linear-gradient(135deg,#1e1b4b,#312e81)", icon: "🌍", accent: "#A78BFA" },
  "DEI & Inclusion":      { grad: "linear-gradient(135deg,#2e1065,#4c1d95)", icon: "🤝", accent: "#C084FC" },
  "Awards & Recognition": { grad: "linear-gradient(135deg,#451a03,#78350f)", icon: "🏆", accent: "#FBBF24" },
  "Wellbeing & Health":   { grad: "linear-gradient(135deg,#052e16,#14532d)", icon: "💚", accent: "#4ADE80" },
  "Events & Upcoming":    { grad: "linear-gradient(135deg,#1e0a00,#7c2d12)", icon: "📅", accent: "#F2805E" },
  "Referral & Jobs":      { grad: "linear-gradient(135deg,#1e1b4b,#2d1b69)", icon: "🚀", accent: "#818CF8" },
  "Newsletter Content":   { grad: "linear-gradient(135deg,#0f172a,#1e293b)", icon: "📰", accent: "#94A3B8" },
};

export const ALL_MONTHS = [
  {
    key: "nov-2024", label: "Nov 2024", short: "Nov", year: 2024, color: "#8B91B5",
    highlight: "Lancement FY25 — Gen AI Summit & Movember",
    emoji: "🍂", articleCount: 77,
    kpis: ["Gen AI Summit 2024 — Perspectives IA & Transformation Digitale", "Programme Digital Explorers — 2e édition lancée"],
    events: ["Gen AI Summit 2024 (Insights IA & Transformation Digitale)", "Movember — Sensibilisation santé masculine", "Kick-Off 2e édition Digital Explorers", "Campagne de sensibilisation programme national"],
    quote: "Novembre 2024 marque le début d'une transformation digitale profonde et d'un engagement humain renouvelé.",
  },
  {
    key: "dec-2024", label: "Déc 2024", short: "Déc", year: 2024, color: "#4ADE80",
    highlight: "Partenariats renforcés & Engagement communautaire",
    emoji: "❄️", articleCount: 6,
    kpis: ["TotalEnergy — collaboration client renforcée", "Forum Ben M'sik — impact communautaire Casablanca"],
    events: ["TotalEnergy — nouveau jalon de collaboration", "London Market Team — rencontre internationale", "Sensibilisation bien-être décembre", "Forum Ben M'sik Casablanca — engagement local"],
    quote: "Décembre 2024 clôture l'année sur des partenariats solides et un engagement communautaire de terrain.",
  },
  {
    key: "jan-2025", label: "Jan 2025", short: "Jan", year: 2025, color: "#FFB476",
    highlight: "ISO 9001 renouvelé & Fort démarrage commercial",
    emoji: "🚀", articleCount: 6,
    kpis: ["Renouvellement ISO 9001 — aucune non-conformité identifiée", "Fort démarrage commercial — succès sur comptes clés"],
    events: ["Renouvellement ISO 9001 — certification qualité confirmée", "Fort démarrage commercial FY25 — succès clients", "Marathon de Séville — notre collègue brille", "Participation auditions CESE (Économie du Soin)"],
    quote: "Janvier 2025 s'ouvre sur un engagement qualité renouvelé et des performances individuelles remarquables.",
  },
  {
    key: "fev-2025", label: "Fév 2025", short: "Fév", year: 2025, color: "#F2805E",
    highlight: "AI Center of Excellence & Town Hall Leadership",
    emoji: "🤖", articleCount: 5,
    kpis: ["Lancement officiel AI Center of Excellence DXC.CDG", "Town Hall Leadership — bilan et perspectives FY25"],
    events: ["Lancement AI Center of Excellence DXC.CDG", "Town Hall avec le Leadership — bilan FY25", "Défi Cooptation — campagne recrutement lancée", "Initiative éco-responsable — engagement durable"],
    quote: "Février 2025 marque l'entrée de DXC.CDG dans l'ère de l'Intelligence Artificielle avec l'AI Center of Excellence.",
  },
  {
    key: "avr-2025", label: "Avr 2025", short: "Avr", year: 2025, color: "#A78BFA",
    highlight: "GITEX Africa 2025 & Kick-Off Charte Managériale FY26",
    emoji: "🌟", articleCount: 7,
    kpis: ["GITEX AFRICA 2025 — présence DXC.CDG à Marrakech", "Séminaire Management — Fort démarrage FY26"],
    events: ["GITEX AFRICA 2025 — Marrakech (bold steps in tech)", "Séminaire Management DXC.CDG — Kick-Off FY26", "Lancement programme Charte Managériale FY26", "Initiatives engagement & partage de valeurs"],
    quote: "Avril 2025 inaugure FY26 avec une vision managériale claire et une présence internationale de premier plan.",
  },
  {
    key: "aout-2025", label: "Aoû 2025", short: "Aoû", year: 2025, color: "#FBBF24",
    highlight: "Champion JMSE & Campagne Référral d'Été",
    emoji: "☀️", articleCount: 7,
    kpis: ["DXC CDG — Champion JMSE 2025 (nouveau titre)", "Campagne Référral Été : 6 000 points par cooptation"],
    events: ["DXC CDG Champion JMSE 2025 — titre renouvelé", "Campagne Référral Été — jusqu'à mi-août", "Mise à jour politique Voyages & Dépenses", "Kick-Off programme Charte Managériale FY26"],
    quote: "L'été 2025 célèbre l'excellence sportive et renforce la culture de recommandation interne.",
  },
  {
    key: "sep-2025", label: "Sep 2025", short: "Sep", year: 2025, color: "#60A5FA",
    highlight: "5 Visites Clients Offshore & OneTeam Rewards",
    emoji: "🤝", articleCount: 9,
    kpis: ["5 visites clients offshore — 1er trimestre FY26", "OneTeam Rewards — Top Collaborateurs célébrés"],
    events: ["5 visites clients offshore prestigieuses (Q1 FY26)", "Succès clients locaux — excellence en action", "OneTeam Rewards — célébration des meilleurs", "Horizons offshore — continuité et nouvelles opportunités"],
    quote: "Septembre 2025 confirme le rayonnement offshore de DXC.CDG avec 5 visites clients de prestige.",
  },
  {
    key: "oct-2025", label: "Oct 2025", short: "Oct", year: 2025, color: "#F87171",
    highlight: "Ethics Week & Marathon de Casablanca",
    emoji: "🏃", articleCount: 6,
    kpis: ["Ethics & Compliance Week 2025 — engagement intégrité", "Marathon de Casablanca — esprit d'équipe DXC.CDG"],
    events: ["Ethics & Compliance Week 2025 — intégrité professionnelle", "DXC.CDG au Marathon de Casablanca — esprit collectif", "Formation efficacité managériale & relationnelle", "Automne d'engagement — Innovation Tech"],
    quote: "Octobre 2025 conjugue intégrité professionnelle et esprit d'équipe à travers des événements marquants.",
  },
  {
    key: "nov-2025", label: "Nov 2025", short: "Nov", year: 2025, color: "#4ADE80",
    highlight: "EU Sales Leadership & Collaboration Globale Renforcée",
    emoji: "🌍", articleCount: 7,
    kpis: ["EU Sales Leadership — présence DXC.CDG reconnue", "Charte Managériale : Flexibilité & Leadership activés"],
    events: ["EU Sales Leadership — collaboration internationale renforcée", "Réalisations clés — rôle stratégique global confirmé", "Charte Managériale : Flexibilité & Agilité managériale", "Assurance maladie simplifiée — bénéfices clarifiés"],
    quote: "Novembre 2025 renforce le positionnement international de DXC.CDG avec le EU Sales Leadership.",
  },
  {
    key: "dec-2025", label: "Déc 2025", short: "Déc", year: 2025, color: "#A78BFA",
    highlight: "4 Trophées Brandon Hall — Reconnaissance Internationale",
    emoji: "🏆", articleCount: 22,
    kpis: ["4 Trophées Brandon Hall 2025 (2 Gold + 1 Gold + 1 Silver)", "OneTeam Rewards Ramadan — bilan et célébration"],
    events: ["Brandon Hall Awards 2025 — 4 distinctions internationales", "OneTeam Rewards édition Ramadan — bilan réussi", "Programme qualité & amélioration continue", "Préparation clôture FY26 — objectifs définis"],
    quote: "Décembre 2025 couronne une année d'excellence par 4 trophées Brandon Hall et une reconnaissance internationale.",
  },
  {
    key: "fev-2026", label: "Fév 2026", short: "Fév", year: 2026, color: "#FBBF24",
    highlight: "Nouveaux Contrats Offshore & Leadership Féminin",
    emoji: "💼", articleCount: 15,
    kpis: ["Nouveaux contrats offshore — portefeuille considérablement enrichi", "SVP Lamiaa Lahiaoui — spotlight leadership féminin national"],
    events: ["Nouveaux contrats — renforcement portefeuille offshore", "Initiatives stratégiques clients clés livrées", "SVP Lamiaa Lahiaoui — spotlight HR Trends 2026", "Programme Recharge & Bien-être Ramadan"],
    quote: "Février 2026 confirme l'expansion offshore et met en lumière l'excellence du leadership féminin DXC.CDG.",
  },
  {
    key: "mars-2026", label: "Mar 2026", short: "Mar", year: 2026, color: "#F2805E",
    highlight: "Clôture FY26 — Résultats Record sur Tous les Fronts",
    emoji: "🏆", articleCount: 7,
    kpis: ["92% participation VOW FY26 — taux record absolu", "ISO 9001 renouvelé sans aucune non-conformité", "4 trophées Brandon Hall · Label RSE CGEM"],
    events: ["GITEX Africa Marrakech — 3e participation consécutive", "1er EMEA Partners Forum Rabat — 80+ leaders européens", "Chess Club 12e mondial · Gaming Club Champion E-League", "Don de sang 21L · 130 vies · Label RSE CGEM", "Partenariat Umnia Bank · Renouvellement Carrefour Italie"],
    quote: "Mars 2026 clôture un FY26 exceptionnel : la confiance des clients et la force du collectif pleinement réunis.",
  },
];

export const YEAR_GROUPS = [
  { year: 2024, label: "FY25 — Semestre 1", color: "#8B91B5", months: ["nov-2024","dec-2024"] },
  { year: 2025, label: "FY25-FY26 — Milieu d'année", color: "#FFB476", months: ["jan-2025","fev-2025","avr-2025","aout-2025","sep-2025","oct-2025","nov-2025","dec-2025"] },
  { year: 2026, label: "FY26 — Clôture", color: "#F2805E", months: ["fev-2026","mars-2026"] },
];
