// src/pages/SavedPage.jsx
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { getSaved, sendSingleItem } from "../services/api";
import { useSaved } from "../hooks/useSaved";
import { Bookmark, X, Download, Mail, ExternalLink } from "lucide-react";
import { jsPDF } from "jspdf";

// PDF generation for saved items
const downloadAsPDF = (item) => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const margin = 20;
  let y = margin;

  // Header
  doc.setFillColor(232, 78, 15); // DXC orange
  doc.rect(0, 0, 210, 18, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('AI Watch · DXC Technology', margin, 12);
  doc.text(new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }), 190, 12, { align: 'right' });

  y = 30;
  doc.setTextColor(30, 30, 30);

  // Category badge
  doc.setFontSize(9);
  doc.setTextColor(232, 78, 15);
  doc.setFont('helvetica', 'bold');
  doc.text((item.item_data?.category || item.item_data?.topic || 'AI Intelligence').toUpperCase(), margin, y);

  y += 8;

  // Title
  doc.setFontSize(18);
  doc.setTextColor(15, 15, 35);
  doc.setFont('helvetica', 'bold');
  const title = item.item_data?.title || item.item_data?.topic || 'Saved Item';
  const titleLines = doc.splitTextToSize(title, 170);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 8 + 4;

  // Meta
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 140);
  doc.setFont('helvetica', 'normal');
  const meta = [item.item_data?.source, item.item_data?.published_at ? new Date(item.item_data.published_at).toLocaleDateString() : ''].filter(Boolean).join(' · ');
  if (meta) { doc.text(meta, margin, y); y += 6; }

  // Divider
  doc.setDrawColor(230, 230, 240);
  doc.line(margin, y, 190, y);
  y += 8;

  // Content
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 60);
  const content = item.item_data?.summary || item.item_data?.description || item.item_data?.content || '';
  if (content) {
    const lines = doc.splitTextToSize(content, 170);
    lines.forEach(line => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(line, margin, y);
      y += 6;
    });
  }

  // For trends: deep dive content
  if (item.item_type === 'trend' && item.item_data?.deep_dive) {
    let dd;
    try {
      dd = typeof item.item_data.deep_dive === 'string'
        ? JSON.parse(item.item_data.deep_dive)
        : item.item_data.deep_dive;
    } catch { dd = null; }

    if (dd) {
      const sections = [
        { title: 'What It Is', content: dd.what_it_is },
        { title: 'Enterprise Impact', content: dd.enterprise_impact },
        { title: 'Action Plan', content: dd.action_plan },
      ];

      sections.forEach(({ title, content }) => {
        if (!content) return;
        if (y > 250) { doc.addPage(); y = 20; }
        y += 6;
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(232, 78, 15);
        doc.text(title, margin, y);
        y += 6;
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(40, 40, 60);
        const lines = doc.splitTextToSize(content, 170);
        lines.forEach(line => {
          if (y > 270) { doc.addPage(); y = 20; }
          doc.text(line, margin, y);
          y += 5.5;
        });
      });
    }
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(160, 160, 180);
  doc.text('Generated by AI Watch · DXC Technology', 105, 287, { align: 'center' });

  const filename = (title).replace(/[^a-z0-9]/gi, '_').slice(0, 40);
  doc.save(`AIWatch_${filename}.pdf`);
};

// Generate HTML content for email
const generateEmailHTML = (item) => {
  const d = item.item_data || {};
  const isArticle = item.item_type === 'article';
  const title = d.title || d.topic || 'Saved Item';
  const category = d.category || d.topic || 'AI Intelligence';
  const signal = d.signal || d.signal_strength || '';
  const source = d.source || '';
  const score = d.score || d.trend_score || '';
  const date = d.published_at ? new Date(d.published_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '';
  const savedDate = item.saved_at ? new Date(item.saved_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '';
  const content = d.summary || d.description || d.content || '';

  let deepDiveHTML = '';
  if (!isArticle && d.deep_dive) {
    let dd;
    try {
      dd = typeof d.deep_dive === 'string' ? JSON.parse(d.deep_dive) : d.deep_dive;
    } catch { dd = null; }

    if (dd) {
      deepDiveHTML = `
        <div style="margin-top: 24px; padding-top: 24px; border-top: 1px solid #e2e4ee;">
          <p style="font-size: 11px; font-weight: 700; color: #E84E0F; letter-spacing: 1px; text-transform: uppercase; margin: 0 0 16px 0;">
            DEEP DIVE ANALYSIS
          </p>
          ${dd.what_it_is ? `
            <div style="margin-bottom: 16px;">
              <p style="font-size: 13px; font-weight: 700; color: #0E1020; margin: 0 0 6px 0;">What It Is</p>
              <p style="font-size: 13px; color: #4a5068; line-height: 1.6; margin: 0;">${dd.what_it_is}</p>
            </div>
          ` : ''}
          ${dd.enterprise_impact ? `
            <div style="margin-bottom: 16px;">
              <p style="font-size: 13px; font-weight: 700; color: #0E1020; margin: 0 0 6px 0;">Enterprise Impact</p>
              <p style="font-size: 13px; color: #4a5068; line-height: 1.6; margin: 0;">${dd.enterprise_impact}</p>
            </div>
          ` : ''}
          ${dd.action_plan ? `
            <div style="margin-bottom: 16px;">
              <p style="font-size: 13px; font-weight: 700; color: #0E1020; margin: 0 0 6px 0;">Action Plan</p>
              <p style="font-size: 13px; color: #4a5068; line-height: 1.6; margin: 0;">${dd.action_plan}</p>
            </div>
          ` : ''}
        </div>
      `;
    }
  }

  // For trends, use a different layout with left border accent
  if (!isArticle) {
    return `
      <div style="border-left: 4px solid #E84E0F; padding: 0 0 0 16px; margin-bottom: 24px;">
        <p style="font-size: 11px; font-weight: 700; color: #E84E0F; letter-spacing: 1px; text-transform: uppercase; margin: 0 0 6px 0;">
          ${category.toUpperCase()}${score ? ` · Score ${score}/10` : ''}
        </p>
        <h2 style="font-size: 20px; font-weight: 800; color: #0E1020; margin: 0 0 8px 0; line-height: 1.3;">
          ${title}
        </h2>
        <p style="font-size: 12px; color: #8b91b5; margin: 0 0 16px 0;">
          ${savedDate ? `Saved: ${savedDate}` : ''}
        </p>
      </div>
      ${content ? `
        <p style="font-size: 14px; color: #2d3050; line-height: 1.7; margin: 0 0 24px 0;">
          ${content}
        </p>
      ` : ''}
      ${deepDiveHTML}
      <div style="background: #f8f9fc; border-radius: 8px; padding: 16px 20px; margin-top: 16px;">
        <p style="font-size: 11px; font-weight: 700; color: #E84E0F; margin: 0 0 8px 0; text-transform: uppercase; letter-spacing: 0.5px;">
          Why it matters
        </p>
        <p style="font-size: 13px; color: #4a5068; line-height: 1.6; margin: 0;">
          This trend was saved to your AI Watch intelligence library${savedDate ? ` on ${savedDate}` : ''}.
          Monitor it for developments that may impact DXC Technology's strategy.
        </p>
      </div>
    `;
  }

  // For articles, use the original layout
  return `
    <div style="margin-bottom: 8px;">
      <span style="display: inline-block; font-size: 10px; font-weight: 700; color: #E84E0F; background: rgba(232, 78, 15, 0.1); padding: 4px 10px; border-radius: 999px; text-transform: uppercase; letter-spacing: 0.5px;">
        ${category}
      </span>
      ${signal ? `
        <span style="display: inline-block; font-size: 10px; font-weight: 700; color: ${signal === 'Strong' ? '#E84E0F' : '#D97706'}; background: ${signal === 'Strong' ? 'rgba(232, 78, 15, 0.1)' : 'rgba(217, 119, 6, 0.1)'}; padding: 4px 10px; border-radius: 999px; margin-left: 6px;">
          ${signal} Signal
        </span>
      ` : ''}
    </div>
    <h2 style="font-size: 20px; font-weight: 800; color: #0E1020; margin: 12px 0 8px 0; line-height: 1.3;">
      ${title}
    </h2>
    <p style="font-size: 12px; color: #8b91b5; margin: 0 0 16px 0;">
      ${[source, date].filter(Boolean).join(' · ')}
    </p>
    ${content ? `
      <p style="font-size: 14px; color: #2d3050; line-height: 1.7; margin: 0;">
        ${content}
      </p>
    ` : ''}
    ${d.url ? `
      <div style="margin-top: 20px;">
        <a href="${d.url}" style="display: inline-block; font-size: 13px; font-weight: 700; color: #E84E0F; text-decoration: none;">
          Read original article →
        </a>
      </div>
    ` : ''}
  `;
};

export default function SavedPage() {
  const navigate = useNavigate();
  const { toggleSave } = useSaved();
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState("all"); // all | article | trend
  const [isMobile, setIsMobile] = useState(window.innerWidth < 600);

  // Drawer state
  const [selectedItem, setSelectedItem] = useState(null);
  const [drawerOpen, setDrawerOpen] = useState(false);

  // Email modal state
  const [emailModalOpen, setEmailModalOpen] = useState(false);
  const [emailTo, setEmailTo] = useState("");
  const [emailSubject, setEmailSubject] = useState("");
  const [emailSending, setEmailSending] = useState(false);
  const [emailError, setEmailError] = useState("");
  const [emailSuccess, setEmailSuccess] = useState(false);

  useEffect(() => {
    const handleResize = () => setIsMobile(window.innerWidth < 600);
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  useEffect(() => {
    setLoading(true);
    getSaved()
      .then(data => setItems(Array.isArray(data) ? data : []))
      .catch(() => setItems([]))
      .finally(() => setLoading(false));
  }, []);

  const handleRemove = async (item) => {
    await toggleSave(item.item_type, item.item_id, item.item_data);
    setItems(prev => prev.filter(i => i.item_id !== item.item_id));
    if (selectedItem?.item_id === item.item_id) {
      setDrawerOpen(false);
      setSelectedItem(null);
    }
  };

  const openDrawer = (item) => {
    setSelectedItem(item);
    setDrawerOpen(true);
  };

  const closeDrawer = () => {
    setDrawerOpen(false);
    setTimeout(() => setSelectedItem(null), 250);
  };

  const openEmailModal = (item) => {
    setSelectedItem(item);
    setEmailTo("");
    setEmailSubject(`AI Watch: ${item.item_data?.title || item.item_data?.topic || 'Intelligence Brief'}`);
    setEmailError("");
    setEmailSuccess(false);
    setEmailModalOpen(true);
  };

  const handleSendEmail = async () => {
    if (!emailTo || !emailTo.includes("@")) {
      setEmailError("Please enter a valid email address");
      return;
    }

    setEmailSending(true);
    setEmailError("");

    try {
      await sendSingleItem({
        to: emailTo,
        subject: emailSubject,
        content_html: generateEmailHTML(selectedItem),
      });
      setEmailSuccess(true);
      setTimeout(() => {
        setEmailModalOpen(false);
        setEmailSuccess(false);
      }, 2000);
    } catch (err) {
      setEmailError(err.message || "Failed to send email");
    } finally {
      setEmailSending(false);
    }
  };

  const displayed = filter === "all" ? items : items.filter(i => i.item_type === filter);

  const articleCount = items.filter(i => i.item_type === "article").length;
  const trendCount = items.filter(i => i.item_type === "trend").length;

  const formatDate = (dateStr) => {
    if (!dateStr) return '';
    return new Date(dateStr).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  };

  return (
    <>
      <style>{`
        @keyframes spin { to { transform: rotate(360deg); } }
        @keyframes slideIn { from { transform: translateX(100%); } to { transform: translateX(0); } }
        @keyframes slideOut { from { transform: translateX(0); } to { transform: translateX(100%); } }
        @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
        .saved-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
          gap: 16px;
        }
        @media (max-width: 600px) {
          .saved-grid {
            grid-template-columns: 1fr;
            gap: 12px;
          }
        }
        .drawer-overlay {
          position: fixed;
          inset: 0;
          background: rgba(0, 0, 0, 0.5);
          z-index: 1000;
          animation: fadeIn 0.2s ease;
        }
        .drawer-panel {
          position: fixed;
          top: 0;
          right: 0;
          bottom: 0;
          width: 480px;
          max-width: 100vw;
          background: var(--bg-surface, #fff);
          border-left: 1px solid var(--border-color, #e2e4ee);
          z-index: 1001;
          display: flex;
          flex-direction: column;
          animation: slideIn 0.25s ease;
        }
        .drawer-panel.closing {
          animation: slideOut 0.25s ease;
        }
        .email-modal-overlay {
          position: fixed;
          inset: 0;
          background: rgba(0, 0, 0, 0.6);
          z-index: 2000;
          display: flex;
          align-items: center;
          justify-content: center;
          animation: fadeIn 0.15s ease;
        }
        .email-modal {
          background: var(--bg-surface, #fff);
          border-radius: 12px;
          width: 400px;
          max-width: 90vw;
          padding: 24px;
          box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
        }
      `}</style>

      {/* Header */}
      <div style={{ marginBottom: isMobile ? 16 : 24 }}>
        <h1 style={{ fontSize: isMobile ? 20 : 24, fontWeight: 700, color: "var(--text-primary)", letterSpacing: -0.5, margin: "0 0 4px" }}>
          Saved Items
        </h1>
        <p style={{ fontSize: isMobile ? 12 : 13, color: "var(--text-muted)", margin: 0 }}>
          {items.length} saved — {articleCount} article{articleCount !== 1 ? "s" : ""}, {trendCount} trend{trendCount !== 1 ? "s" : ""}
        </p>
      </div>

      {/* Filter tabs */}
      <div className="filter-chips-scroll" style={{
        display: "flex",
        gap: 8,
        marginBottom: isMobile ? 16 : 24,
        overflowX: isMobile ? "auto" : "visible",
        paddingBottom: isMobile ? 4 : 0,
      }}>
        {[
          { id: "all", label: `All (${items.length})` },
          { id: "article", label: `Articles (${articleCount})` },
          { id: "trend", label: `Trends (${trendCount})` },
        ].map(f => (
          <button
            key={f.id}
            onClick={() => setFilter(f.id)}
            style={{
              padding: isMobile ? "6px 14px" : "8px 18px",
              borderRadius: 999,
              border: `1.5px solid ${filter === f.id ? "var(--accent)" : "var(--border-color)"}`,
              background: filter === f.id ? "var(--accent)" : "var(--card-bg)",
              color: filter === f.id ? "#fff" : "var(--text-muted)",
              fontSize: isMobile ? 12 : 13,
              fontWeight: 600,
              cursor: "pointer",
              transition: "all 0.15s",
              whiteSpace: "nowrap",
              flexShrink: 0,
            }}
          >{f.label}</button>
        ))}
      </div>

      {/* Loading */}
      {loading && (
        <div style={{ textAlign: "center", padding: "60px 0", color: "var(--text-muted)", fontSize: 13 }}>
          <div style={{
            width: 32, height: 32, margin: "0 auto 12px",
            border: "3px solid var(--border-color)", borderTop: "3px solid var(--orange)",
            borderRadius: "50%", animation: "spin 0.8s linear infinite",
          }} />
          Loading saved items…
        </div>
      )}

      {/* Empty state */}
      {!loading && displayed.length === 0 && (
        <div style={{
          textAlign: "center",
          padding: isMobile ? "40px 16px" : "60px 20px",
          background: "var(--surface)",
          borderRadius: 10,
          border: "1px solid var(--border-color)",
        }}>
          <Bookmark size={isMobile ? 28 : 36} strokeWidth={1.5} style={{ color: "var(--text-muted)", marginBottom: 12 }} />
          <div style={{ fontSize: isMobile ? 14 : 15, fontWeight: 700, color: "var(--text-secondary)", marginBottom: 8 }}>
            Nothing saved yet
          </div>
          <div style={{ fontSize: isMobile ? 12 : 13, color: "var(--text-muted)", marginBottom: isMobile ? 20 : 24, lineHeight: 1.6 }}>
            Click the bookmark icon on any article or trend to save it here.
          </div>
          <div style={{
            display: "flex",
            flexDirection: isMobile ? "column" : "row",
            gap: 10,
            justifyContent: "center",
          }}>
            <button
              onClick={() => navigate("/feed")}
              style={{
                padding: "9px 20px", borderRadius: 7, border: "none",
                background: "var(--orange)", color: "#fff", fontSize: 13, fontWeight: 700, cursor: "pointer",
                width: isMobile ? "100%" : "auto",
              }}
            >Browse Articles</button>
            <button
              onClick={() => navigate("/trends")}
              style={{
                padding: "9px 20px", borderRadius: 7, border: "1.5px solid var(--border-color)",
                background: "var(--card-bg)", color: "var(--text-secondary)", fontSize: 13, fontWeight: 600, cursor: "pointer",
                width: isMobile ? "100%" : "auto",
              }}
            >Browse Trends</button>
          </div>
        </div>
      )}

      {/* Items grid */}
      {!loading && displayed.length > 0 && (
        <div className="saved-grid">
          {displayed.map(item => {
            const isArticle = item.item_type === "article";
            const d = item.item_data || {};

            if (isArticle) {
              return (
                <div
                  key={item.item_id}
                  onClick={() => openDrawer(item)}
                  style={{
                    background: "var(--card-bg)",
                    border: "1px solid var(--border-color)",
                    borderRadius: 8,
                    padding: isMobile ? "16px" : "20px 24px",
                    cursor: "pointer",
                    transition: "border-color 0.15s",
                    overflow: "hidden",
                    minWidth: 0,
                  }}
                  onMouseEnter={e => e.currentTarget.style.borderColor = "var(--accent)"}
                  onMouseLeave={e => e.currentTarget.style.borderColor = "var(--border-color)"}
                >
                  <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12, marginBottom: 10, minWidth: 0 }}>
                    <h3 style={{
                      fontSize: isMobile ? 14 : 15,
                      fontWeight: 600,
                      color: "var(--text-primary)",
                      flex: 1,
                      lineHeight: 1.4,
                      margin: 0,
                      minWidth: 0,
                      wordWrap: "break-word",
                      overflowWrap: "break-word",
                      display: "-webkit-box",
                      WebkitLineClamp: 2,
                      WebkitBoxOrient: "vertical",
                      overflow: "hidden",
                    }}>
                      {d.title || "Untitled Article"}
                    </h3>
                    <button
                      onClick={e => { e.stopPropagation(); handleRemove(item); }}
                      style={{ background: "none", border: "none", cursor: "pointer", color: "var(--orange)", fontSize: 16, flexShrink: 0, padding: 2 }}
                    >
                      <Bookmark size={16} fill="var(--orange)" />
                    </button>
                  </div>
                  {d.summary && (
                    <p style={{
                      fontSize: isMobile ? 13 : 14,
                      color: "var(--text-secondary)",
                      lineHeight: 1.6,
                      overflow: "hidden",
                      display: "-webkit-box",
                      WebkitLineClamp: isMobile ? 2 : 3,
                      WebkitBoxOrient: "vertical",
                      margin: 0,
                      marginBottom: 12,
                    }}>
                      {d.summary}
                    </p>
                  )}
                  <div style={{
                    fontSize: isMobile ? 11 : 12,
                    color: "var(--text-muted)",
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    flexWrap: "wrap",
                    gap: 8,
                  }}>
                    <span style={{
                      overflow: "hidden",
                      textOverflow: "ellipsis",
                      whiteSpace: "nowrap",
                      minWidth: 0,
                      flex: 1,
                    }}>{d.category || d.topic || "General"} · {d.source || ""} · {formatDate(item.saved_at)}</span>
                  </div>
                </div>
              );
            } else {
              return (
                <div
                  key={item.item_id}
                  onClick={() => openDrawer(item)}
                  style={{
                    background: "var(--card-bg)",
                    border: "1px solid var(--border-color)",
                    borderRadius: 8,
                    padding: isMobile ? "16px" : "20px 24px",
                    cursor: "pointer",
                    transition: "border-color 0.15s",
                    overflow: "hidden",
                    minWidth: 0,
                  }}
                  onMouseEnter={e => e.currentTarget.style.borderColor = "var(--accent)"}
                  onMouseLeave={e => e.currentTarget.style.borderColor = "var(--border-color)"}
                >
                  <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12, marginBottom: 8 }}>
                    <div style={{ fontSize: isMobile ? 24 : 28, fontWeight: 500, color: "var(--accent)" }}>
                      {d.trend_score || 7}
                    </div>
                    <button
                      onClick={e => { e.stopPropagation(); handleRemove(item); }}
                      style={{ background: "none", border: "none", cursor: "pointer", color: "var(--orange)", fontSize: 16, flexShrink: 0, padding: 2 }}
                    >
                      <Bookmark size={16} fill="var(--orange)" />
                    </button>
                  </div>
                  <h3 style={{
                    fontSize: isMobile ? 13 : 14,
                    fontWeight: 600,
                    color: "var(--text-primary)",
                    margin: 0,
                    marginBottom: 4,
                    minWidth: 0,
                    wordWrap: "break-word",
                    overflowWrap: "break-word",
                    display: "-webkit-box",
                    WebkitLineClamp: 2,
                    WebkitBoxOrient: "vertical",
                    overflow: "hidden",
                  }}>
                    {d.topic || d.title || "Unknown Topic"}
                  </h3>
                  <div style={{ fontSize: isMobile ? 10 : 11, color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: 0.5 }}>
                    {d.category || "Technology"}
                  </div>
                </div>
              );
            }
          })}
        </div>
      )}

      {/* Drawer overlay & panel */}
      {drawerOpen && selectedItem && (
        <>
          <div className="drawer-overlay" onClick={closeDrawer} />
          <div className="drawer-panel">
            {/* Drawer header */}
            <div style={{
              padding: "20px 24px",
              borderBottom: "1px solid var(--border-color)",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              flexShrink: 0,
            }}>
              <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                <span style={{
                  fontSize: 10,
                  fontWeight: 700,
                  padding: "4px 10px",
                  borderRadius: 999,
                  background: "var(--accent-dim, rgba(232, 78, 15, 0.1))",
                  color: "var(--accent)",
                  textTransform: "uppercase",
                  letterSpacing: 0.5,
                }}>
                  {selectedItem.item_data?.category || selectedItem.item_data?.topic || "AI"}
                </span>
                {selectedItem.item_data?.signal_strength && (
                  <span style={{
                    fontSize: 10,
                    fontWeight: 700,
                    padding: "4px 10px",
                    borderRadius: 999,
                    background: selectedItem.item_data.signal_strength === "Strong" ? "var(--orange-light, rgba(232, 78, 15, 0.1))" : "var(--amber-light, rgba(217, 119, 6, 0.1))",
                    color: selectedItem.item_data.signal_strength === "Strong" ? "var(--orange)" : "var(--amber)",
                  }}>
                    {selectedItem.item_data.signal_strength}
                  </span>
                )}
                {selectedItem.item_type === "trend" && selectedItem.item_data?.trend_score && (
                  <span style={{
                    fontSize: 10,
                    fontWeight: 700,
                    padding: "4px 10px",
                    borderRadius: 999,
                    background: "var(--accent-dim, rgba(232, 78, 15, 0.1))",
                    color: "var(--accent)",
                  }}>
                    Score: {selectedItem.item_data.trend_score}/10
                  </span>
                )}
              </div>
              <button
                onClick={closeDrawer}
                style={{
                  background: "none",
                  border: "none",
                  cursor: "pointer",
                  color: "var(--text-muted)",
                  padding: 4,
                }}
              >
                <X size={20} />
              </button>
            </div>

            {/* Drawer content */}
            <div style={{ flex: 1, overflowY: "auto", padding: "24px 32px" }}>
              <h2 style={{
                fontSize: 20,
                fontWeight: 700,
                color: "var(--text-primary)",
                lineHeight: 1.3,
                margin: "0 0 8px 0",
              }}>
                {selectedItem.item_data?.title || selectedItem.item_data?.topic || "Untitled"}
              </h2>

              <div style={{
                fontSize: 12,
                color: "var(--text-muted)",
                marginBottom: 20,
              }}>
                {[
                  selectedItem.item_data?.source,
                  selectedItem.item_data?.published_at ? new Date(selectedItem.item_data.published_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : null,
                  selectedItem.item_type === "trend" ? `Detected: ${formatDate(selectedItem.saved_at)}` : null,
                ].filter(Boolean).join(" · ")}
              </div>

              <div style={{ height: 1, background: "var(--border-color)", marginBottom: 20 }} />

              {/* Content */}
              <div style={{
                fontSize: 14,
                color: "var(--text-secondary)",
                lineHeight: 1.7,
                marginBottom: 24,
              }}>
                {selectedItem.item_data?.summary || selectedItem.item_data?.description || selectedItem.item_data?.content || "No content available."}
              </div>

              {/* Deep dive for trends */}
              {selectedItem.item_type === "trend" && selectedItem.item_data?.deep_dive && (() => {
                let dd;
                try {
                  dd = typeof selectedItem.item_data.deep_dive === 'string'
                    ? JSON.parse(selectedItem.item_data.deep_dive)
                    : selectedItem.item_data.deep_dive;
                } catch { dd = null; }

                if (!dd) return null;

                return (
                  <div style={{
                    background: "var(--surface, #f8f9fc)",
                    borderRadius: 8,
                    padding: 20,
                    marginBottom: 24,
                  }}>
                    <div style={{
                      fontSize: 11,
                      fontWeight: 700,
                      color: "var(--accent)",
                      letterSpacing: 1,
                      textTransform: "uppercase",
                      marginBottom: 16,
                    }}>
                      Deep Dive Analysis
                    </div>

                    {dd.what_it_is && (
                      <div style={{ marginBottom: 16 }}>
                        <div style={{ fontSize: 13, fontWeight: 700, color: "var(--text-primary)", marginBottom: 6 }}>What It Is</div>
                        <div style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.6 }}>{dd.what_it_is}</div>
                      </div>
                    )}

                    {dd.enterprise_impact && (
                      <div style={{ marginBottom: 16 }}>
                        <div style={{ fontSize: 13, fontWeight: 700, color: "var(--text-primary)", marginBottom: 6 }}>Enterprise Impact</div>
                        <div style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.6 }}>{dd.enterprise_impact}</div>
                      </div>
                    )}

                    {dd.action_plan && (
                      <div>
                        <div style={{ fontSize: 13, fontWeight: 700, color: "var(--text-primary)", marginBottom: 6 }}>Action Plan</div>
                        <div style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.6 }}>{dd.action_plan}</div>
                      </div>
                    )}
                  </div>
                );
              })()}

              {/* Sources for trends */}
              {selectedItem.item_type === "trend" && selectedItem.item_data?.sources && (
                <div style={{ marginBottom: 24 }}>
                  <div style={{ fontSize: 12, fontWeight: 700, color: "var(--text-muted)", marginBottom: 8 }}>Sources</div>
                  <div style={{ fontSize: 13, color: "var(--text-secondary)" }}>
                    {Array.isArray(selectedItem.item_data.sources)
                      ? selectedItem.item_data.sources.join(", ")
                      : selectedItem.item_data.sources}
                  </div>
                </div>
              )}
            </div>

            {/* Drawer actions */}
            <div style={{
              padding: "16px 24px",
              borderTop: "1px solid var(--border-color)",
              display: "flex",
              gap: 10,
              flexShrink: 0,
            }}>
              {selectedItem.item_data?.url && (
                <a
                  href={selectedItem.item_data.url}
                  target="_blank"
                  rel="noreferrer"
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 6,
                    padding: "10px 16px",
                    borderRadius: 8,
                    border: "1.5px solid var(--border-color)",
                    background: "var(--card-bg)",
                    color: "var(--text-primary)",
                    fontSize: 13,
                    fontWeight: 600,
                    textDecoration: "none",
                    cursor: "pointer",
                  }}
                >
                  <ExternalLink size={14} />
                  Read original
                </a>
              )}
              <button
                onClick={() => downloadAsPDF(selectedItem)}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 6,
                  padding: "10px 16px",
                  borderRadius: 8,
                  border: "none",
                  background: "var(--accent)",
                  color: "#fff",
                  fontSize: 13,
                  fontWeight: 600,
                  cursor: "pointer",
                }}
              >
                <Download size={14} />
                PDF
              </button>
              <button
                onClick={() => openEmailModal(selectedItem)}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 6,
                  padding: "10px 16px",
                  borderRadius: 8,
                  border: "none",
                  background: "var(--accent)",
                  color: "#fff",
                  fontSize: 13,
                  fontWeight: 600,
                  cursor: "pointer",
                }}
              >
                <Mail size={14} />
                Send
              </button>
            </div>
          </div>
        </>
      )}

      {/* Email modal */}
      {emailModalOpen && selectedItem && (
        <div className="email-modal-overlay" onClick={() => setEmailModalOpen(false)}>
          <div className="email-modal" onClick={e => e.stopPropagation()}>
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 20 }}>
              <h3 style={{ fontSize: 16, fontWeight: 700, color: "var(--text-primary)", margin: 0 }}>
                Send via Email
              </h3>
              <button
                onClick={() => setEmailModalOpen(false)}
                style={{ background: "none", border: "none", cursor: "pointer", color: "var(--text-muted)", padding: 4 }}
              >
                <X size={18} />
              </button>
            </div>

            {emailSuccess ? (
              <div style={{
                textAlign: "center",
                padding: "24px 0",
                color: "var(--delta-color, #22c55e)",
              }}>
                <div style={{ fontSize: 32, marginBottom: 8 }}>✓</div>
                <div style={{ fontSize: 14, fontWeight: 600 }}>Email sent successfully!</div>
              </div>
            ) : (
              <>
                <div style={{ marginBottom: 16 }}>
                  <label style={{
                    fontSize: 11,
                    fontWeight: 700,
                    color: "var(--text-muted)",
                    letterSpacing: 0.5,
                    textTransform: "uppercase",
                    display: "block",
                    marginBottom: 6,
                  }}>To</label>
                  <input
                    type="email"
                    value={emailTo}
                    onChange={e => setEmailTo(e.target.value)}
                    placeholder="email@example.com"
                    style={{
                      width: "100%",
                      height: 42,
                      padding: "0 14px",
                      border: "1.5px solid var(--border-color)",
                      borderRadius: 8,
                      fontSize: 14,
                      outline: "none",
                      boxSizing: "border-box",
                      background: "var(--input-bg, #fff)",
                      color: "var(--text-primary)",
                    }}
                    onFocus={e => { e.target.style.borderColor = "var(--accent)"; }}
                    onBlur={e => { e.target.style.borderColor = "var(--border-color)"; }}
                  />
                </div>

                <div style={{ marginBottom: 20 }}>
                  <label style={{
                    fontSize: 11,
                    fontWeight: 700,
                    color: "var(--text-muted)",
                    letterSpacing: 0.5,
                    textTransform: "uppercase",
                    display: "block",
                    marginBottom: 6,
                  }}>Subject</label>
                  <input
                    type="text"
                    value={emailSubject}
                    onChange={e => setEmailSubject(e.target.value)}
                    style={{
                      width: "100%",
                      height: 42,
                      padding: "0 14px",
                      border: "1.5px solid var(--border-color)",
                      borderRadius: 8,
                      fontSize: 14,
                      outline: "none",
                      boxSizing: "border-box",
                      background: "var(--input-bg, #fff)",
                      color: "var(--text-primary)",
                    }}
                    onFocus={e => { e.target.style.borderColor = "var(--accent)"; }}
                    onBlur={e => { e.target.style.borderColor = "var(--border-color)"; }}
                  />
                </div>

                {emailError && (
                  <div style={{
                    fontSize: 13,
                    color: "#dc3545",
                    marginBottom: 16,
                    padding: "10px 14px",
                    background: "rgba(220,53,69,0.1)",
                    border: "1px solid rgba(220,53,69,0.3)",
                    borderRadius: 8,
                  }}>
                    {emailError.includes('authentication') || emailError.includes('SMTP')
                      ? '⚠️ Email not configured. Ask admin to set Gmail App Password.'
                      : emailError.includes('Not Found') || emailError === 'Not Found'
                      ? '⚠️ Email service not available. Restart the backend server.'
                      : `⚠️ ${emailError}`
                    }
                  </div>
                )}

                <div style={{ display: "flex", gap: 10, justifyContent: "flex-end" }}>
                  <button
                    onClick={() => setEmailModalOpen(false)}
                    style={{
                      padding: "10px 20px",
                      borderRadius: 8,
                      border: "1.5px solid var(--border-color)",
                      background: "var(--card-bg)",
                      color: "var(--text-secondary)",
                      fontSize: 13,
                      fontWeight: 600,
                      cursor: "pointer",
                    }}
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleSendEmail}
                    disabled={emailSending}
                    style={{
                      padding: "10px 20px",
                      borderRadius: 8,
                      border: "none",
                      background: emailSending ? "var(--border-color)" : "var(--accent)",
                      color: "#fff",
                      fontSize: 13,
                      fontWeight: 600,
                      cursor: emailSending ? "default" : "pointer",
                    }}
                  >
                    {emailSending ? "Sending…" : "Send Email"}
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      )}
    </>
  );
}
